### ISSUE TITLE
Tensorflow not working with PCL (numeric_types.h)

### ISSUE THREAD

**Issue by armandok** [FloopCZ/tensorflow_cc#101]
Hello,
I am getting compile errors when I use tensorflow_cc and PCL libraries together.
This is my CMakesLists.txt file:

`cmake_minimum_required (VERSION 2.8.12)
project (myproject)

find_package (TensorflowCC REQUIRED)
find_package(OpenCV 3.3 REQUIRED)
find_package(Eigen3 3.1.0 REQUIRED)
find_package(PCL 1.3 REQUIRED COMPONENTS common io)

include_directories (
    ${PROJECT_SOURCE_DIR}
    ${PROJECT_BINARY_DIR}
    ${PCL_INCLUDE_DIRS}
    ${OpenCV_INCLUDE_DIRS}
    ${EIGEN3_INCLUDE_DIR}
)

add_library (myprojectLib SHARED
    ObjectDetector.cpp
    src/opencv_odometry/depth_to_3d.cpp
    src/opencv_odometry/normal.cpp
    src/opencv_odometry/odometry.cpp
)

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/lib)

#add_definitions(${PCL_DEFINITIONS})

target_link_libraries(myprojectLib
    TensorflowCC::Shared
    ${OpenCV_LIBS}
    ${EIGEN3_LIBS}
    ${PCL_COMMON_LIBRARIES}
    ${PCL_IO_LIBRARIES}
)

add_executable(myproject main.cpp)
target_link_libraries(myproject myprojectLib)`

The errors that I get are:

> /usr/local/include/tensorflow/tensorflow/core/framework/numeric_types.h:-1: In static member function ‘static tensorflow::bfloat16 Eigen::NumTraits<tensorflow::bfloat16>::infinity()’:
/usr/local/include/tensorflow/tensorflow/core/framework/numeric_types.h:78: error: ‘infinity’ is not a member of ‘Eigen::NumTraits<float>’
     return FloatToBFloat16(NumTraits<float>::infinity());

> /usr/local/include/tensorflow/tensorflow/core/framework/numeric_types.h:82: error: ‘quiet_NaN’ is not a member of ‘Eigen::NumTraits<float>’
>      return FloatToBFloat16(NumTraits<float>::quiet_NaN());

> /usr/local/include/tensorflow/tensorflow/core/framework/numeric_types.h:94: error: ‘log’ is not a template function
>      const tensorflow::bfloat16& x) {

> /usr/local/include/tensorflow/tensorflow/core/framework/numeric_types.h:100: error: ‘exp’ is not a template function
>      const tensorflow::bfloat16& x) {

> /usr/local/include/tensorflow/tensorflow/core/framework/numeric_types.h:106: error: ‘abs’ is not a template function
>      const tensorflow::bfloat16& x) {

PCL depends on Eigen, and I think this might be an incompatibility between different versions of Eigen library but I'm not sure.
My code works without PCL, but when I try to include the PCL package I get the above errors.
Any ideas?

**Comment by FloopCZ** [comment]
Yes, it may easily be an incompatibility between Eigen versions. Have you tried to skip the
```
find_package(Eigen3 3.1.0 REQUIRED)
```
?

One Eigen version is already provided with `tensorflow_cc`.

**Comment by armandok** [comment]
Yes, I did. It didn't change anything since PCL finds the Eigen library anyway because it depends on it.
Any suggestions on how to fix this?

**Comment by FloopCZ** [comment]
I have no suggestions at the moment. You could try to remove the eigen dependency (i.e., delete https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/CMakeLists.txt#L70) to see if it helps.

**Comment by FloopCZ** [comment]
Is your issue solved?

**Comment by soohwan-hyun** [comment]
I have the same problem as @armandok written.
and I tried the above, but failed. Could you tell me any suggestion?

**Comment by FloopCZ** [comment]
Maybe @armandok can help? Has he solved the issue?

**Comment by armandok** [comment]
Sorry for the late reply.
I cleared the find_package line in my CMakeslist file and did a clean build and it worked.

**Comment by zeroAska** [comment]
@armandok I had exactly the same issue here. How did you clear the find_package line in the cmakelist file? Did you change your package's cmake list file, or tensorflow_cc's? Thanks!

**Comment by jappoz** [comment]
Hi, I have this problem as well...
Can someone explain how to solve this?
Thanks

**Comment by armandok** [comment]
If I remember correctly, I removed the find eigen part from my package's cmake list file and compiled it.
