### ISSUE TITLE
No supported CUDA compiler available

### ISSUE THREAD

**Issue by achalshah20** [FloopCZ/tensorflow_cc#104]
Cuda 9.2 is out. Which supports gcc 7 now.

When I tried to run this script, I got error like "No supported CUDA compiler available.". I backtraced it to build_tensorflow.sh where you are manually checking all different gcc version.

I feel it is not a good idea as it's gonna get broken for every cuda major/gcc release. It is better to give option to use to choose right version of gcc just like tensorflow does with bazel.

PR #103 fixes this issue for now. But it does some structural change so its upto @FloopCZ to accept it.

**Comment by FloopCZ** [comment]
As described in #105, you can change the compiler version using environmental variable, similarly to all other TF options. The current defaults and README specifies `gcc5` as a dependency, so it should work on Ubuntu 16.04, 18.04 and Arch.

If you wish to use a different compiler, the you should be able to
```
export GCC_HOST_COMPILER_PATH=gcc-7
```
before the `make` command to do so.

**Comment by achalshah20** [comment]
Atleast it should have proper message, because only from "No supported CUDA compiler available" error, I didn't know I needed to export gcc-7. I dug up the code and the I knew.
