### ISSUE TITLE
Move tensorflow flags to head cmake

### ISSUE THREAD

**Issue by achalshah20** [FloopCZ/tensorflow_cc#105]
Currently, if someone wants to modify tensorflow build related options they have to go through build_tensorflow and modify each of them. 

We should move all these options to head cmake. So, users can modify it by cmake graphics tools easily.
Example: PR #103

```
export CC_OPT_FLAGS=${CC_OPT_FLAGS:-"-march=ivybridge"}
export TF_NEED_GCP=${TF_NEED_GCP:-0}
export TF_NEED_HDFS=${TF_NEED_HDFS:-0}
export TF_NEED_OPENCL=${TF_NEED_OPENCL:-0}
export TF_NEED_OPENCL_SYCL=${TF_NEED_OPENCL_SYCL:-0}
export TF_NEED_TENSORRT=${TF_NEED_TENSORRT:-0}
export TF_NEED_JEMALLOC=${TF_NEED_JEMALLOC:-1}
export TF_NEED_VERBS=${TF_NEED_VERBS:-0}
export TF_NEED_MKL=${TF_NEED_MKL:-1}
export TF_DOWNLOAD_MKL=${TF_DOWNLOAD_MKL:-1}
export TF_NEED_MPI=${TF_NEED_MPI:-0}
export TF_ENABLE_XLA=${TF_ENABLE_XLA:-1}
export TF_NEED_S3=${TF_NEED_S3:-0}
export TF_NEED_GDR=${TF_NEED_GDR:-0}
export TF_CUDA_CLANG=${TF_CUDA_CLANG:-0}
export TF_SET_ANDROID_WORKSPACE=${TF_SET_ANDROID_WORKSPACE:-0}
export TF_NEED_KAFKA=${TF_NEED_KAFKA:-0}
export TF_DOWNLOAD_CLANG=${TF_DOWNLOAD_CLANG:-0}
export TF_NCCL_VERSION=${TF_NCCL_VERSION:-1.3}  # _DEFAULT_NCCL_VERSION from configure.py
export PYTHON_BIN_PATH=${PYTHON_BIN_PATH:-"$(which python3)"}
export PYTHON_LIB_PATH="$($PYTHON_BIN_PATH -c 'import site; print(site.getsitepackages()[0])')"
```

**Comment by FloopCZ** [comment]
This syntax allows you to use environmental variables to modify these options. Just e.g.,
```
export TF_NEED_JEMALLOC=0
```
before the `make` and the option you provided will be used instead of the default specified in `build_tensorflow.sh`.

**Comment by achalshah20** [comment]
Yes. But it should be customizable. Why would I manually export everything in console before building tensorflow_cc? To build any program, ideal pipeline for building any c++ package is, we customize cmake options and build/install.
