### ISSUE TITLE
build error  while  build the example code. 

### ISSUE THREAD

**Issue by KangDaehern** [FloopCZ/tensorflow_cc#112]
Hello. 
I was compile your   example code. Then  get the below  error message.. 

Could you help  why below error is occurred? 

During the  step  --> cmake ..
       
*** Error message**** 
kangdaehern@kangdaehern-Samsung-DeskTop-System:~/c++_project/tensorflow_samples/tensorflow_cc/example/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:5 (find_package):
  By not providing "FindTensorflowCC.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "TensorflowCC", but CMake did not find one.

  Could not find a package configuration file provided by "TensorflowCC" with
  any of the following names:

    TensorflowCCConfig.cmake
    tensorflowcc-config.cmake

  Add the installation prefix of "TensorflowCC" to CMAKE_PREFIX_PATH or set
  "TensorflowCC_DIR" to a directory containing one of the above files.  If
  "TensorflowCC" provides a separate development package or SDK, be sure it
  has been installed.

CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "FindTensorflowCC.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "TensorflowCC", but CMake did not find one.

  Could not find a package configuration file provided by "TensorflowCC" with
  any of the following names:

    TensorflowCCConfig.cmake
    tensorflowcc-config.cmake

  Add the installation prefix of "TensorflowCC" to CMAKE_PREFIX_PATH or set
  "TensorflowCC_DIR" to a directory containing one of the above files.  If
  "TensorflowCC" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/kangdaehern/c++_project/tensorflow_samples/tensorflow_cc/example/build/CMakeFiles/CMakeOutput.log".

**Comment by KangDaehern** [comment]
Sorry.  I found the reason for above  error messages. 
I forgot the   below  step  in your tutorial document.  
After  doing below step, issue is fixed. 
 
cd tensorflow_cc
mkdir build && cd build
# for static library only:
cmake ..
# for shared library only (requires Bazel):
# cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON ..
make && sudo make install

**Comment by FloopCZ** [comment]
Great.

**Comment by sathyamoorthyrr** [comment]
@FloopCZ @KangDaehern 
I'm getting the same error while compiling for static library. I ran,

`cd tensorflow_cc`
`mkdir build && cd build`
`cmake ..`

Then inside example folder,
`mkdir build && cd build`
`cmake ..`

It didn't worked. so I tried,
`cd tensorflow_cc`
`mkdir build && cd build`
`cmake ..`

and then,
`make`

It compiled several things for sometime.

Again, I ran,
inside example folder,
`mkdir build && cd build`
`cmake`

**Comment by FloopCZ** [comment]
Please closely follow the `README.md`. You need to run `make && sudo make install` also after the first `cmake ..` while still in the `tensorflow_cc` folder (see step 3 in the README).

**Comment by sathyamoorthyrr** [comment]
> Please closely follow the `README.md`. You need to run `make && sudo make install` also after the first `cmake ..` while still in the `tensorflow_cc` folder (see step 3 in the README).

Thank you very much. was confused by this line,
`# for shared library only (requires Bazel):`

By the way, could you shed light on how is this method to build different from the method in [official repo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile)?

**Comment by FloopCZ** [comment]
The build process is very similar to the one described in the official repo. See [build_tensorflow.sh.in](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/build_tensorflow.sh.in). What is novel in this repo is the installation procedure - `make install` installs the required headers and libraries to the operating system and creates the corresponding CMake targets for easier use (and without Bazel).

**Comment by sathyamoorthyrr** [comment]
> The build process is very similar to the one described in the official repo. See [build_tensorflow.sh.in](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/build_tensorflow.sh.in). What is novel in this repo is the installation procedure - `make install` installs the required headers and libraries to the operating system and creates the corresponding CMake targets for easier use (and without Bazel).

Thank you.
By following the appropriate procedures in main repo, I could generate,
`tensorflow/contrib/makefile/gen/lib/libtensorflow-core.a`

How could I make use of this? any idea?

Would you look at [this](https://stackoverflow.com/questions/54573573/how-to-run-tensorflow-code-in-c-with-cmake-using-static-library)?

**Comment by FloopCZ** [comment]
You can compile your code by manually providing all the necessary tensorflow headers to your compiler and linking against the static library. But this `tensorflow_cc` project is here exactly for this purpose - to make this process easier so that you don't need to search for all the necessary headers manually by yourself.

**Comment by sathyamoorthyrr** [comment]
Great work! Kudos!

Should I build this `tensorflow_cc` project for every platform(Linux, Windows, Mac) again?

Actually, I need to deploy(only model inference) using C++ into production.
How can I use this repo for production scenario?

**Comment by FloopCZ** [comment]
This project officially only supports Linux, so on Win and Mac, you are on your own. And there is no difference between development and production, so just install and build as usual.

**Comment by sathyamoorthyrr** [comment]
Okay.
To know,
Where(Under which directory) should I place my `.cpp`, `BUILD` files in the main [repo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile) after building it?

Should I create a new folder for my project in main repository tree?

**Comment by FloopCZ** [comment]
No, you can create your own project completely independently from the main repo or this repo. Try it by putting the [example folder](https://github.com/FloopCZ/tensorflow_cc/tree/master/example) from this repo into any folder you want (e.g., `/tmp/example`) and running the build commands from there and it should work as expected.

**Comment by sathyamoorthyrr** [comment]
As mentioned, I copied this repo's **example** folder into main repo's root.
Hope I've to run `tensorflow/contrib/makefile/build_all_linux.sh` as mentioned in main repo to build.
Cmake stuff!!
right?

I did ran.

This does not make use of the already generated `tensorflow/contrib/makefile/gen/lib/libtensorflow-core.a`
It seems to build all the way form scratch.
Am I doing right?

**Comment by FloopCZ** [comment]
No, the main TF repo has nothing to do with this, if you want to use this project or one of the examples, just delete the main TF repo, you don't need it and you don't need to run any scripts from it. Just build the example using CMake.
