### ISSUE TITLE
Setting TENSORFLOW_TAG "v1.9.0rc1" fails

### ISSUE THREAD

**Issue by jmtatsch** [FloopCZ/tensorflow_cc#114]
directly altering it in TensorflowBase.cmake works. 
Aren't the curly braces too much `GIT_TAG "${TENSORFLOW_TAG}"
`?

**Comment by FloopCZ** [comment]
What is the error message? Have you entered it correctly (it should be "v1.9.0-rc1", note the hyphen)?

**Comment by jmtatsch** [comment]
You are right, everything works as expected with the hyphen.
