### ISSUE TITLE
System Protobuf not working

### ISSUE THREAD

**Issue by omaralvarez** [FloopCZ/tensorflow_cc#115]
I have protobuf 3.4.0 installed in my system. I am using ```cmake -DSYSTEM_PROTOBUF=ON ..```:

```
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /usr/local/lib/libprotobuf.so;-lpthread (found version "3.4.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: ../tensorflow_cc/tensorflow_cc/build
```

When linking my external project with cmake I get lots of:

```
#error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
```

My best guess is that protobuf includes from third party are still being copied when I make install, and are being picked up by cmake. Since current TF protobuf version is 3.5.0 there is a version mismatch.

Am I doing something wrong? Any ideas?

**Comment by FloopCZ** [comment]
Please when you build your extenal project using `make`, set env variable `VERBOSE` to `1` to see the compiler and linker invocation. That is:
```
VERBOSE=1 make
```

**Comment by omaralvarez** [comment]
```
-isystem /usr/local/include/tensorflow/tensorflow/contrib/makefile/gen/proto -isystem /usr/local/include/tensorflow/tensorflow/contrib/makefile/gen/proto_text
```

I think those includes are not correct, my protobuf is not installed there. I should mention I am compiling static TF, and when it builds TF I see protobuf being compiled (not sure if relevant).

**Comment by FloopCZ** [comment]
This is strange, yes. Can you please provide the full compiler command including all the flags? Or even the full output of `VERBOSE=1 make`?

**Comment by omaralvarez** [comment]
Of course:

```
/usr/bin/c++   -DUSE_CUDNN -DUSE_LEVELDB -DUSE_LMDB -DUSE_OPENCV -Ddeeplearn_EXPORTS -I/usr/include/eigen3 -isystem /usr/local/include -isystem /usr/local/include/opencv -I/home/mads/omaralv/deeplearning/libdeeplearn/include -I/home/mads/omaralv/deeplearning/libdeeplearn/src -isystem /opt/synthetrick/include -isystem /usr/include/hdf5/serial -isystem /usr/local/cuda-9.1/include -isystem /mnt/data/devel/opencv/build -isystem /mnt/data/devel/opencv/include -isystem /mnt/data/devel/opencv/include/opencv -isystem /mnt/data/devel/opencv/modules/core/include -isystem /mnt/data/devel/opencv/modules/flann/include -isystem /mnt/data/devel/opencv_contrib/modules/hdf/include -isystem /mnt/data/devel/opencv/modules/imgproc/include -isystem /mnt/data/devel/opencv/modules/ml/include -isystem /mnt/data/devel/opencv/modules/objdetect/include -isystem /mnt/data/devel/opencv_contrib/modules/phase_unwrapping/include -isystem /mnt/data/devel/opencv/modules/photo/include -isystem /mnt/data/devel/opencv_contrib/modules/plot/include -isystem /mnt/data/devel/opencv_contrib/modules/reg/include -isystem /mnt/data/devel/opencv_contrib/modules/surface_matching/include -isystem /mnt/data/devel/opencv/modules/video/include -isystem /mnt/data/devel/opencv_contrib/modules/xphoto/include -isystem /mnt/data/devel/opencv/modules/dnn/include -isystem /mnt/data/devel/opencv_contrib/modules/freetype/include -isystem /mnt/data/devel/opencv_contrib/modules/fuzzy/include -isystem /mnt/data/devel/opencv_contrib/modules/hfs/include -isystem /mnt/data/devel/opencv_contrib/modules/img_hash/include -isystem /mnt/data/devel/opencv/modules/imgcodecs/include -isystem /mnt/data/devel/opencv/modules/shape/include -isystem /mnt/data/devel/opencv/modules/videoio/include -isystem /mnt/data/devel/opencv_contrib/modules/xobjdetect/include -isystem /mnt/data/devel/opencv/modules/highgui/include -isystem /mnt/data/devel/opencv/modules/superres/include -isystem /mnt/data/devel/opencv/modules/ts/include -isystem /mnt/data/devel/opencv_contrib/modules/bioinspired/include -isystem /mnt/data/devel/opencv_contrib/modules/dnn_objdetect/include -isystem /mnt/data/devel/opencv_contrib/modules/dpm/include -isystem /mnt/data/devel/opencv/modules/features2d/include -isystem /mnt/data/devel/opencv_contrib/modules/line_descriptor/include -isystem /mnt/data/devel/opencv_contrib/modules/saliency/include -isystem /mnt/data/devel/opencv_contrib/modules/text/include -isystem /mnt/data/devel/opencv/modules/calib3d/include -isystem /mnt/data/devel/opencv_contrib/modules/ccalib/include -isystem /mnt/data/devel/opencv_contrib/modules/datasets/include -isystem /mnt/data/devel/opencv_contrib/modules/rgbd/include -isystem /mnt/data/devel/opencv_contrib/modules/stereo/include -isystem /mnt/data/devel/opencv_contrib/modules/structured_light/include -isystem /mnt/data/devel/opencv_contrib/modules/tracking/include -isystem /mnt/data/devel/opencv/modules/videostab/include -isystem /mnt/data/devel/opencv_contrib/modules/xfeatures2d/include -isystem /mnt/data/devel/opencv_contrib/modules/ximgproc/include -isystem /mnt/data/devel/opencv_contrib/modules/aruco/include -isystem /mnt/data/devel/opencv_contrib/modules/bgsegm/include -isystem /mnt/data/devel/opencv_contrib/modules/face/include -isystem /mnt/data/devel/opencv_contrib/modules/optflow/include -isystem /mnt/data/devel/opencv_contrib/modules/sfm/include -isystem /mnt/data/devel/opencv/modules/stitching/include -isystem /usr/include/atlas -isystem /mnt/data/devel/caffe/include -isystem /usr/local/include/tensorflow -isystem /usr/local/include/tensorflow/tensorflow/contrib/makefile/gen/host_obj -isystem /usr/local/include/tensorflow/tensorflow/contrib/makefile/downloads -isystem /usr/local/include/tensorflow/tensorflow/contrib/makefile/downloads/eigen -isystem /usr/local/include/tensorflow/tensorflow/contrib/makefile/downloads/gemmlowp -isystem /usr/local/include/tensorflow/tensorflow/contrib/makefile/downloads/nsync/public -isystem /usr/local/include/tensorflow/tensorflow/contrib/makefile/gen/proto -isystem /usr/local/include/tensorflow/tensorflow/contrib/makefile/gen/proto_text  -O3 -DNDEBUG -fPIC   -std=c++11 -std=gnu++11 -o Tensorflow.cpp.o -c Tensorflow.cpp
```

**Comment by FloopCZ** [comment]
Sorry for the delay. Unfortunately, at this moment the protobuf in your system needs to be newer than the one TF is built with. The `SYSTEM_PROTOBUF` is not meant to replace the protobuf version TF is built with, but the protobuf version your program is linked against. If those two are incompatible, it will fail.

[TF contrib/makefile](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile) scripts that we utilize, they just download and build the version of protobuf compatible with the current TF version and it would be hacky (and in my opinion, not worth the effort) to force them to use a different one. Of course, if anyone is interested, PRs are welcome, but the right place to extend the functionality is probably the TF [contrib/makefile](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile) repository itself.

**Comment by omaralvarez** [comment]
I don't understand what is the point of the ```SYSTEM_PROTOBUF``` flag. Even if I have a newer protobuf version, my program won't be able to compile, as soon as you have a discrepancy in the protobuf version, nothing will compile (version errors in includes from different protobuf versions). It does not matter if TF complains or other libraries, the fact is that if protobuf versions are not the same, it won't compile.

What would be a typical scenario in which the flag is useful? Just so I can test in my machine. The problem I have is that I have a couple of other projects that use protobuf, and I need to be able to link everything together.

**Comment by FloopCZ** [comment]
You are right, the `-DSYSTEM_PROTOBUF` is not meant to allow different protobuf versions. It is meant to avoid name collisions. Some people had problems with name collisions when `tensorflow_cc` was introduced into their program, because some other part of their program also published the same `protobuf` functions. So `-DSYSTEM_PROTOBUF` was introduced to allow linking all the dependencies of their program against a single shared library. Unfortunately, the protobuf version needs to match the one TensorFlow requires.

**Comment by omaralvarez** [comment]
Thanks for the information. I now have a clearer unserstanding of what the option does. I'm going to close the issue, since it is not a bug. Great work!
