### ISSUE TITLE
OLDER TENSORFLOW VERSION

### ISSUE THREAD

**Issue by hellbago** [FloopCZ/tensorflow_cc#116]
What must I do if i want to use this project within an older tensorflow version, for example tf 1.4? @FloopCZ

**Comment by achalshah20** [comment]
You can go to head CMakeLists.txt file and change this line to according version.


`set(TENSORFLOW_TAG "v1.8.0" CACHE STRING "The tensorflow release tag to be checked out (default v1.8.0).")
`

**Comment by FloopCZ** [comment]
Passing it as a CMake argument:
```
cmake -DTENSORFLOW_TAG="v1.4.0" .......
```
should also work. But I really cannot guarantee that older TF versions will work properly. This repo should be considered to be a rolling release.
