### ISSUE TITLE
error while loading shared libraries: libcusolver.so.9.2

### ISSUE THREAD

**Issue by szm2015** [FloopCZ/tensorflow_cc#119]
Hi,

I get the error mentioned in the title when I try to run my C++ code. I have CUDA 9.2 and cuDNN 7.1 on Ubuntu 18.04 and the path /usr/local/cuda/lib64/ (which contains the required library libcusolver.so.9.2) has been added to LD_LIBRARY_PATH. These are the last output lines of make command:

`Target //tensorflow:libtensorflow_cc.so up-to-date:
  bazel-bin/tensorflow/libtensorflow_cc.so
INFO: Elapsed time: 9050.715s, Critical Path: 598.55s
INFO: 5433 processes: 5433 local.
INFO: Build completed successfully, 6588 total actions
Replacing links with the copies of their targets.
This may take a while...
[ 87%] No build step for 'tensorflow_shared'
[ 93%] No install step for 'tensorflow_shared'
[100%] Completed 'tensorflow_shared'
[100%] Built target tensorflow_shared`

I have also installed TensorFlow version 1.9.0 from source (my bazel version is 0.15.0) and it seems to work without a problem (I have tested it with import tensorflow as tf and then tf.__version__). Also, I have been using tensorflow_cc for a while and because I have installed a new version of Ubuntu I now have to install everything from scratch including this project.

Thanks in advance for your help.

**Comment by FloopCZ** [comment]
Can you please provide the output of `ldd your_program` ? It seems that your CUDA installation is broken.

**Comment by szm2015** [comment]
The output of ldd as you asked:

    linux-vdso.so.1 (0x00007ffc46db0000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
(0x00007fddd47f1000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fddd45e9000)
    libopencv_imgcodecs.so.3.4 =>
/home/szm/Software/opencv-3.4.1/Build/lib/libopencv_imgcodecs.so.3.4
(0x00007fddd3e70000)
    libopencv_core.so.3.4 =>
/home/szm/Software/opencv-3.4.1/Build/lib/libopencv_core.so.3.4
(0x00007fddd2f65000)
    libopencv_imgproc.so.3.4 =>
/home/szm/Software/opencv-3.4.1/Build/lib/libopencv_imgproc.so.3.4
(0x00007fddd06b6000)
    libtensorflow_cc.so => /usr/local/lib/tensorflow_cc/libtensorflow_cc.so
(0x00007fddb1a3c000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(0x00007fddb16ae000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fddb1310000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1
(0x00007fddb10f8000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fddb0d07000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fddd4c53000)
    libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16
(0x00007fddb0ad5000)
    libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5
(0x00007fddb085e000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fddb0641000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fddb043d000)
    libcusolver.so.9.2 => /usr/local/cuda/lib64/libcusolver.so.9.2
(0x00007fdda8ffc000)
    libcublas.so.9.2 => /usr/local/cuda/lib64/libcublas.so.9.2
(0x00007fdda55ae000)
    libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1
(0x00007fdda462e000)
    libcudnn.so.7 => /usr/local/cuda/lib64/libcudnn.so.7
(0x00007fdd8ffae000)
    libcufft.so.9.2 => /usr/local/cuda/lib64/libcufft.so.9.2
(0x00007fdd8a954000)
    libcurand.so.9.2 => /usr/local/cuda/lib64/libcurand.so.9.2
(0x00007fdd86a16000)
    libcudart.so.9.2 => /usr/local/cuda/lib64/libcudart.so.9.2
(0x00007fdd867ac000)
    libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1
(0x00007fdd8657c000)
    liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fdd86356000)
    libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0
(0x00007fdd86148000)
    libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8
(0x00007fdd85ee0000)
    libnvidia-fatbinaryloader.so.396.24 =>
/usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.396.24
(0x00007fdd85c94000)

**Comment by szm2015** [comment]
This is the output of device_Query:
`./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GTX 850M"
  CUDA Driver Version / Runtime Version          9.2 / 9.2
  CUDA Capability Major/Minor version number:    5.0
  Total amount of global memory:                 4046 MBytes (4242604032 bytes)
  ( 5) Multiprocessors, (128) CUDA Cores/MP:     640 CUDA Cores
  GPU Max Clock rate:                            902 MHz (0.90 GHz)
  Memory Clock rate:                             900 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 2097152 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            No
  Supports Cooperative Kernel Launch:            No
  Supports MultiDevice Co-op Kernel Launch:      No
  Device PCI Domain ID / Bus ID / location ID:   0 / 10 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 9.2, CUDA Runtime Version = 9.2, NumDevs = 1
Result = PASS
`

**Comment by FloopCZ** [comment]
```
    libcusolver.so.9.2 => /usr/local/cuda/lib64/libcusolver.so.9.2
    libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1
```
Is it possible that you have two installations of cuda - one from the official NVIDIA installer and one from the package manager?

**Comment by szm2015** [comment]
Well, during the last week I have installed various CUDAs (9.0, 9.1 and
9.2) and each of them has been installed from run files. Each time I first
removed the previous installation by simply deleting the cuda-9.x and cuda
directory from /us/local/ and then proceeding with the installation. I have
installed the driver using Additional Drivers from Software & Updates
(nvidia-driver-396, It may be worth to note that I also have
nvidia-driver-390 in my installed packages but it only has 20 kB of disk
space). Therefore, the driver aside, I always install CUDA by extracting
the run file and then executing the two cuda run files. As long as I'm
concerned I have never installed CUDA from package manager or anything
other than run file. What does this line imply?


libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1

**Comment by szm2015** [comment]
Hello again. 
I tested my tensorflow installation by running a demo training using TF-Slim. As that demo worked all right, I think that my CUDA has been installed without a problem and that tensorflow works. Now it seems that the problem is with tensorflow_cc or the way it has been installed on my system. I really appreciate any help. Thank you.

**Comment by FloopCZ** [comment]
The Python TF library can possibly link the libraries differently. Take a look at:
```
ldd /usr/lib/python3.6/site-packages/tensorflow/libtensorflow_framework.so
```
(or wherever you have your Python TF installed, maybe `~/.local/lib/python3.6/...`)

Mine, for instance, does not need `libcusolver` at all.

**Comment by szm2015** [comment]
Hi,
This is the output I get for this command:
    linux-vdso.so.1 (0x00007ffc2b57f000)
    libcublas.so.9.2 => /usr/local/cuda/lib64/libcublas.so.9.2
(0x00007fbd36455000)
    libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1
(0x00007fbd354d5000)
    libcudnn.so.7 => /usr/local/cuda/lib64/libcudnn.so.7
(0x00007fbd20e55000)
    libcufft.so.9.2 => /usr/local/cuda/lib64/libcufft.so.9.2
(0x00007fbd1b7fb000)
    libcurand.so.9.2 => /usr/local/cuda/lib64/libcurand.so.9.2
(0x00007fbd178bd000)
    libcudart.so.9.2 => /usr/local/cuda/lib64/libcudart.so.9.2
(0x00007fbd17653000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbd1744f000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbd170b1000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
(0x00007fbd16e92000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(0x00007fbd16b04000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1
(0x00007fbd168ec000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbd164fb000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fbd3ae69000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fbd162f3000)
    libnvidia-fatbinaryloader.so.396.24 =>
/usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.396.24
(0x00007fbd160a7000)

It doesn't show libcusolver either. So, What can I do now to get
tensorflow_cc to work?

**Comment by FloopCZ** [comment]
I guess your `libcusolver.so` is broken, so I would try to uninstall all the CUDAs that were installed previously remove all the remaining CUDA files (confirm with `find / -name "*cuda*"`), reboot and install a single new CUDA.

**Comment by szm2015** [comment]
Well, the problem was that Qt (the IDE I'm using) couldn't see
LD_LIBRARY_PATH for some reason and I had to set it in the app itself. I
never had to do such a thing before so it didn't occur to me that it could
be the source of the problem until I tried to run the code in terminal and
it worked. Thank you for the time you dedicated for this and sorry for my
ignorance :)

**Comment by FloopCZ** [comment]
Glad you fixed it.
