### ISSUE TITLE
compile shared library occurs problems

### ISSUE THREAD

**Issue by ddxu** [FloopCZ/tensorflow_cc#12]
@FloopCZ  Thank you for your project~
I have followed your installation guide trying to build shared library, but meet errors as follows:

`compile_linux_protobuf.sh finished successfully!!!
CUDA support disabled
Warning: ignoring LD_PRELOAD in environment.
..........
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Configuration finished
Warning: ignoring LD_PRELOAD in environment.
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: /home/user/tensorflow_cc_dynamic/tensorflow_cc/build/tensorflow/third_party/py/python_configure.bzl:285:20: unexpected keyword 'environ' in call to repository_rule(implementation: function, *, attrs: dict or NoneType = None, local: bool = False).
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'third_party/py/python_configure.bzl' has errors.
INFO: Elapsed time: 18.851s
make[2]: *** [tensorflow-stamp/tensorflow_shared-configure] Error 1
make[1]: *** [CMakeFiles/tensorflow_shared.dir/all] Error 2
make: *** [all] Error 2`

My server's system is centos7. One fact is that I have successfully built the static library as your guide, and run your demo code successfully. But when use the static library to create a session from a .pb file (as following bold sentence),  the status.ok() is not true. So I guess the static library doesn't support this api. So I have to build shared library but don't know how to fix the problems above mentioned.
**Status status = session->Create(graph_def);**

Hope for your reply~

**Comment by ddxu** [comment]
Problem solved. refer [https://github.com/tensorflow/tensorflow/issues/8738]
 update bazel to 0.4.5 and retry.

**Comment by FloopCZ** [comment]
Issues solved before I even read them are the best issues.
