### ISSUE TITLE
Add a flag to disable GPU support while building shared library

### ISSUE THREAD

**Issue by suisuiwudi** [FloopCZ/tensorflow_cc#124]
I've already installed my CUDA which version is 9.0, but I don't need GPU support now and would like to build a shared library.

CUDA detection code is located in `build_tensorflow.sh`, so I changed it to disable GPU support.

TensorFlow default installation is on CPU, appreciate it if you could follow this.

And it would be great you could set another library like tensorflow::shared-cpu or shared-gpu.

Anyway, thanks for the guide.

**Comment by FloopCZ** [comment]
Hi, you can try #126:
```
cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON -DALLOW_CUDA=OFF ..
```

**Comment by suisuiwudi** [comment]
Great! Thank you for the quick update.
