### ISSUE TITLE
find_package problem

### ISSUE THREAD

**Issue by payas** [FloopCZ/tensorflow_cc#13]
hello, every step in the readme for building static works great, except the example, I got:

payas@ubuntu:~/tensorflow_cc/example/build$ **uname -a**
Linux ubuntu 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
payas@ubuntu:~/tensorflow_cc/example/build$ **cmake ..**
-- Configuring done
CMake Error at CMakeLists.txt:2 (add_executable):
  Target "example" links to target "TensorflowCC::Static" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

-- Generating done
-- Build files have been written to: /home/payas/tensorflow_cc/example/build
payas@ubuntu:~/tensorflow_cc/example/build$ 

 what I miss?

**Comment by FloopCZ** [comment]
Hi, this seems like you have not installed the library using `make install` or you have installed it to a folder not in your path. Can you try to run `make install` once over and show us where does the process store the `TensorflowCCConfig.cmake` file?

**Comment by payas** [comment]
yes, everything gets installed on /usr/local/

[ 50%] Built target tensorflow_base
[100%] Built target tensorflow_static
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/include/tensorflow
-- Up-to-date: /usr/local/include/tensorflow/tensorflow
-- Up-to-date: /usr/local/include/tensorflow/tensorflow/cc
-- Up-to-date: /usr/local/include/tensorflow/tensorflow/cc/training
**..... a million files more ...**
-- Up-to-date: /usr/local/include/tensorflow/third_party/fft2d/BUILD
-- Up-to-date: /usr/local/lib/tensorflow_cc/libprotobuf.a
-- Up-to-date: /usr/local/lib/tensorflow_cc/libtensorflow-core.a
-- Up-to-date: /usr/local/lib/cmake/TensorflowCC/TensorflowCCStaticTargets.cmake
-- Up-to-date: /usr/local/lib/cmake/TensorflowCC/TensorflowCCConfig.cmake
-- Up-to-date: /usr/local/lib/cmake/TensorflowCC/TensorflowCCConfigVersion.cmake

**Comment by payas** [comment]
forget it...
I delete all build/ folders and start again and everything builds just perfect.

I'm really sorry men!

**Comment by FloopCZ** [comment]
It happens, glad you solved it! ;-)
