### ISSUE TITLE
Is it possible to install tensorflow_cc on a system with no internet access?

### ISSUE THREAD

**Issue by szm2015** [FloopCZ/tensorflow_cc#135]
Hi,
The question is simple. I have a system with no internet access (it's complicated!) and I want to install tensorflow_cc on it. The required packages are not a problem. However, as the code downloads various files during installation, I was wondering if there's a way to get around this? People say that for Tensorflow itself we can download the .whl file from another system and then install it on the target one, though I have never tried such a thing. Is there a similar solution for tensorflow_cc? Thank you.

**Comment by FloopCZ** [comment]
You can build it on one computer, migrate the whole folder to other computer and run just `make install`.

**Comment by szm2015** [comment]
Thank you, but once I built it on my own system and the make command went
on through its end. Then I restarted the system. When I went back to
install it and ran make install, it just started the whole make process all
over again and downloaded the packages once more. So, won't the same thing
happen if I transfer the build directory to another system?

در تاریخ پنجشنبه ۳۰ اوت ۲۰۱۸،‏ ۱:۴۴ Filip Matzner <notifications@github.com>
نوشت:

**Comment by FloopCZ** [comment]
Hmm, this should not happe . If it is built successfully and you run make install, it should not rebuild. Wasn't there a build error?

**Comment by FloopCZ** [comment]
Try whether it installs, reboot, try again. It should not rebuild after
reboot.

**Comment by szm2015** [comment]
Thank you I will try it again. One question though, I think that this
process is more prone to runtime errors as the library has been built on
another system. For example, should the driver version be the same in both
systems? or would the CPU architecture matter?

**Comment by FloopCZ** [comment]
Cpu march is defaulted to rather generic type and the same driver major
version should suffice.
