### ISSUE TITLE
error on Ubuntu14.04

### ISSUE THREAD

**Issue by newpoo** [FloopCZ/tensorflow_cc#138]
I am using Ubuntu 14.04 and could tried both g++7 and g++6.

Have spent quite some time on it and couldn't figure out the cause of the follow errors. Any inputs? Thank you!

compile_linux_protobuf.sh finished successfully!!!
PROTOC = "/opt/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc"
CC_PREFIX = ""
/tmp/ccwWCXTd.s: Assembler messages:
/tmp/ccwWCXTd.s:6897: Error: operand type mismatch for `vxorps'
make[3]: *** [/opt/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/lib/wav/wav_io.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/tmp/ccx7Iqob.s: Assembler messages:
/tmp/ccx7Iqob.s:5870: Error: no such instruction: `kmovb .LC11(%rip),%k1'
/tmp/ccx7Iqob.s:5873: Error: no such instruction: `kmovb %eax,%k2'
/tmp/ccx7Iqob.s:5900: Error: no such instruction: `kmovb .LC11(%rip),%k1'
/tmp/ccx7Iqob.s:5903: Error: no such instruction: `kmovb %eax,%k2'
make[3]: *** [/opt/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/obj/tensorflow/contrib/makefile/downloads/fft2d/fftsg.o] Error 1
/tmp/ccjSPIcg.s: Assembler messages:
/tmp/ccjSPIcg.s:799: Error: operand type mismatch for `vxorps'
make[3]: *** [/opt/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/lib/random/distribution_sampler.o] Error 1
make[2]: *** [tensorflow-stamp/tensorflow_static-configure] Error 2
make[1]: *** [CMakeFiles/tensorflow_static.dir/all] Error 2
make: *** [all] Error 2

**Comment by FloopCZ** [comment]
Hi, I am sorry, but Ubuntu 14.04 is not supported. I am not sure what is the cause of those assembler errors, but it may be that the build process uses an old compiler version.
