### ISSUE TITLE
Tensorflow 1.11 support

### ISSUE THREAD

**Issue by mmstick** [FloopCZ/tensorflow_cc#142]
I was able to get this to work. It requires two fixes due to the official release being broken.

1. First, you need to modify `TensorFlowBase.cmake` like so, as tensorflow is supposed to be building protobuf 3.6.0, but they forgot to update their URL for it, and so it downloads 3.5.0 instead, which causes compiler errors if try to build anything with TF.

```diff
  cmake_minimum_required(VERSION 3.3 FATAL_ERROR)
  include(ExternalProject)
  
+ set(OLD_PROTOBUF "https://mirror.bazel.build/github.com/google/protobuf/archive/396336eb961b75f03b25824fe86cf6490fb75e3a.tar.gz")
+ set(FIXED_PROTOBUF "https://github.com/protocolbuffers/protobuf/releases/download/v3.6.0/protobuf-all-3.6.0.tar.gz")
  
  ExternalProject_Add(
    tensorflow_base
    GIT_REPOSITORY https://github.com/tensorflow/tensorflow.git
    GIT_TAG "${TENSORFLOW_TAG}"
    TMP_DIR "/tmp"
    STAMP_DIR "tensorflow-stamp"
    DOWNLOAD_DIR "tensorflow"
    SOURCE_DIR "tensorflow"
    BUILD_IN_SOURCE 1
    UPDATE_COMMAND ""
    CONFIGURE_COMMAND make -f tensorflow/contrib/makefile/Makefile clean
+             COMMAND sed -i "s#${OLD_PROTOBUF}#${FIXED_PROTOBUF}#g" tensorflow/contrib/makefile/download_dependencies.sh
              COMMAND tensorflow/contrib/makefile/download_dependencies.sh
    BUILD_COMMAND ""
    INSTALL_COMMAND ""
  )
```

2. Then you need to symlink `tensorflow/contrib/makefile/downloads/absl/absl` to `include/tensorflow/absl`.

**Comment by FloopCZ** [comment]
Cool, thank you, I will try that! Have you considered a pull request to the upstream tensorflow repo?

**Comment by mmstick** [comment]
As always, they have only fixed these things on the master branch, and these fixes aren't being carried back to the official tarballs / tagged releases.
