### ISSUE TITLE
Set custom installation directory

### ISSUE THREAD

**Issue by usptact** [FloopCZ/tensorflow_cc#146]
I am curious whether it is possible to define a custom installation directory for the compiled libraries/headers and other files. Is there a flag that can be passed to CMake that will tell to use this path as a root for installation?

I see CMake install commands in the main CMakeLists.txt but I can't clearly see what to modify for this to happen. Maybe I am missing something obvious.

**Comment by FloopCZ** [comment]
Hi, yes, it is a standard CMake option called `CMAKE_INSTALL_PREFIX`. Use like this:
```
cmake -DCMAKE_INSTALL_PREFIX=~/.local ..
```
(don't forget the `-D` at the beginning as with any other CMake option)
