### ISSUE TITLE
absl headers

### ISSUE THREAD

**Issue by kevindarby** [FloopCZ/tensorflow_cc#148]
absl/ header files seem to be missing from the install

```
In file included from ../../externals/linux/include/tensorflow/core/lib/core/status.h:24:0,
                 from ../../src/lib/ml/tfloader.h:5,
                 from ../../src/lib/ml/tfloader.cpp:1:
../../externals/linux/include/tensorflow/core/lib/core/stringpiece.h:29:10: fatal error: absl/strings/string_view.h: No such file or directory
 #include "absl/strings/string_view.h"
```

probably related to this: https://github.com/tensorflow/tensorflow/issues/22007 but I wonder if a workaround in this project is worthwhile.

**Comment by FloopCZ** [comment]
Interesting, those should be included: https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/CMakeLists.txt#L75

Were you able to solve this?

**Comment by kevindarby** [comment]
I was not able to figure this out, I just did the workaround described here.

https://github.com/tensorflow/tensorflow/issues/22007#issuecomment-437769016

**Comment by FloopCZ** [comment]
Absl is now provided only through bazel build, so it should not be a problem anymore.
