### ISSUE TITLE
cross-compiling for ARM

### ISSUE THREAD

**Issue by mixaz** [FloopCZ/tensorflow_cc#151]
I'm considering cross-compilation tensorflow_cc for ARM arch. I tried https://github.com/lhelontra/tensorflow-on-arm and it works OK, but it uses Bazel and builds shared library only, while static one would be better for me, and I do not need python  packages. I do not like Bazel and cmake looks better for me.

So my question is how to cross-compile tensorflow_cc for ARM, I'm using https://github.com/dockcross/dockcross docker images for that.

Please advice what needs to be changed in tensorflow_cc for cross-compiling - probably CC_OPT_FLAGS, anything else? I'm going to set CC options per tensorflow-on-arm config for my arch (Beaglebone Black) https://github.com/lhelontra/tensorflow-on-arm/blob/master/build_tensorflow/configs/beagle_black.conf#L26 - will it be enough to enable TF optimization for my CPU (NEON SIMD in particular)? I'm new with TF, so I'm not sure if TF ARM toolchain may enable something special in Bazel build.

Thanks in advance!

**Comment by mixaz** [comment]
Please disregard my previous comment - it was a broken curl executable in my docker image derived from dockcross one. 

Now I got further:
```
checking whether we are cross compiling... configure: error: in `/work/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/downloads/protobuf':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
CMakeFiles/tensorflow_static.dir/build.make:106: recipe for target 'tensorflow-stamp/tensorflow_static-configure' failed
make[2]: *** [tensorflow-stamp/tensorflow_static-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tensorflow_static.dir/all' failed
```

**Comment by FloopCZ** [comment]
Hi, you are courageous. :-) I believe a better place to ask these questions is the TensorFlow itself - specifically the `contrib/makefile` section.
