### ISSUE TITLE
Building tensorflow_cc on centos 7

### ISSUE THREAD

**Issue by danperrett** [FloopCZ/tensorflow_cc#155]
Hi,
I'm trying to build FloopCZ/tensorflow_cc on Centos 7 ( have no choice with this).
Everything seem to go OK until it gets to a certain stage in build whereby it just freezes.
below is the last stages:

is this actually complete or is there more to go?
why is it then stalling?

----------------------------------------------------------------------
Libraries have been installed in:
   /home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/bin'
  /bin/sh ../libtool   --mode=install /bin/install -c protoc '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/bin'
libtool: install: /bin/install -c .libs/protoc /home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/bin/protoc
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include'
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf'
 /bin/install -c -m 644  google/protobuf/descriptor.proto google/protobuf/any.proto google/protobuf/api.proto google/protobuf/duration.proto google/protobuf/empty.proto google/protobuf/field_mask.proto google/protobuf/source_context.proto google/protobuf/struct.proto google/protobuf/timestamp.proto google/protobuf/type.proto google/protobuf/wrappers.proto '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf'
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler'
 /bin/install -c -m 644  google/protobuf/compiler/plugin.proto '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler'
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include'
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf'
 /bin/install -c -m 644  google/protobuf/any.pb.h google/protobuf/api.pb.h google/protobuf/any.h google/protobuf/arena.h google/protobuf/arena_impl.h google/protobuf/arenastring.h google/protobuf/descriptor_database.h google/protobuf/descriptor.h google/protobuf/descriptor.pb.h google/protobuf/duration.pb.h google/protobuf/dynamic_message.h google/protobuf/empty.pb.h google/protobuf/extension_set.h google/protobuf/field_mask.pb.h google/protobuf/generated_enum_reflection.h google/protobuf/generated_enum_util.h google/protobuf/generated_message_reflection.h google/protobuf/generated_message_table_driven.h google/protobuf/generated_message_util.h google/protobuf/has_bits.h google/protobuf/implicit_weak_message.h google/protobuf/inlined_string_field.h google/protobuf/map_entry.h google/protobuf/map_entry_lite.h google/protobuf/map_field.h google/protobuf/map_field_inl.h google/protobuf/map_field_lite.h google/protobuf/map.h google/protobuf/map_type_handler.h google/protobuf/message.h google/protobuf/message_lite.h google/protobuf/metadata.h google/protobuf/metadata_lite.h google/protobuf/reflection.h google/protobuf/reflection_ops.h google/protobuf/repeated_field.h google/protobuf/service.h google/protobuf/source_context.pb.h google/protobuf/struct.pb.h google/protobuf/text_format.h '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf'
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler/java'
 /bin/install -c -m 644  google/protobuf/compiler/java/java_generator.h google/protobuf/compiler/java/java_names.h '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler/java'
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler/cpp'
 /bin/install -c -m 644  google/protobuf/compiler/cpp/cpp_generator.h '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler/cpp'
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler/python'
 /bin/install -c -m 644  google/protobuf/compiler/python/python_generator.h '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler/python'
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler/js'
 /bin/install -c -m 644  google/protobuf/compiler/js/js_generator.h google/protobuf/compiler/js/well_known_types_embed.h '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler/js'
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf'
 /bin/install -c -m 644  google/protobuf/timestamp.pb.h google/protobuf/type.pb.h google/protobuf/unknown_field_set.h google/protobuf/wire_format.h google/protobuf/wire_format_lite.h google/protobuf/wire_format_lite_inl.h google/protobuf/wrappers.pb.h '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf'
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/stubs'
 /bin/install -c -m 644  google/protobuf/stubs/callback.h google/protobuf/stubs/bytestream.h google/protobuf/stubs/casts.h google/protobuf/stubs/common.h google/protobuf/stubs/fastmem.h google/protobuf/stubs/hash.h google/protobuf/stubs/logging.h google/protobuf/stubs/macros.h google/protobuf/stubs/mutex.h google/protobuf/stubs/once.h google/protobuf/stubs/platform_macros.h google/protobuf/stubs/port.h google/protobuf/stubs/singleton.h google/protobuf/stubs/status.h google/protobuf/stubs/stl_util.h google/protobuf/stubs/stringpiece.h google/protobuf/stubs/template_util.h '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/stubs'
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/util'
 /bin/install -c -m 644  google/protobuf/util/type_resolver.h google/protobuf/util/delimited_message_util.h google/protobuf/util/field_comparator.h google/protobuf/util/field_mask_util.h google/protobuf/util/json_util.h google/protobuf/util/time_util.h google/protobuf/util/type_resolver_util.h google/protobuf/util/message_differencer.h '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/util'
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler/php'
 /bin/install -c -m 644  google/protobuf/compiler/php/php_generator.h '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler/php'
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler'
 /bin/install -c -m 644  google/protobuf/compiler/code_generator.h google/protobuf/compiler/command_line_interface.h google/protobuf/compiler/importer.h google/protobuf/compiler/parser.h google/protobuf/compiler/plugin.h google/protobuf/compiler/plugin.pb.h '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler'
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler/ruby'
 /bin/install -c -m 644  google/protobuf/compiler/ruby/ruby_generator.h '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler/ruby'
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/io'
 /bin/install -c -m 644  google/protobuf/io/coded_stream.h google/protobuf/io/gzip_stream.h google/protobuf/io/printer.h google/protobuf/io/strtod.h google/protobuf/io/tokenizer.h google/protobuf/io/zero_copy_stream.h google/protobuf/io/zero_copy_stream_impl.h google/protobuf/io/zero_copy_stream_impl_lite.h '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/io'
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler/csharp'
 /bin/install -c -m 644  google/protobuf/compiler/csharp/csharp_generator.h google/protobuf/compiler/csharp/csharp_names.h '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler/csharp'
 /bin/mkdir -p '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler/objectivec'
 /bin/install -c -m 644  google/protobuf/compiler/objectivec/objectivec_generator.h google/protobuf/compiler/objectivec/objectivec_helpers.h '/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include/google/protobuf/compiler/objectivec'
compile_linux_protobuf.sh finished successfully!!!
PROTOC = "/home/dperrett/tensorflow_cc/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc"
CC_PREFIX = ""

**Comment by FloopCZ** [comment]
And are you sure it is stalled? What about your CPU usage, RAM usage, swap usage, etc? (see e.g. `htop` command) The compilation can take quite some time.

**Comment by danperrett** [comment]
yes it just needed a lot of time. thansk.
