### ISSUE TITLE
How to compile linux lib with MKL?

### ISSUE THREAD

**Issue by songmeixu** [FloopCZ/tensorflow_cc#156]
Hi! I found out that MKL flags is set by default:
https://github.com/FloopCZ/tensorflow_cc/blob/e1ad656883d16f404a5638a218cd197dbfdc0f08/tensorflow_cc/cmake/build_tensorflow.sh.in#L19-L20
But the compiled static lib seems not with MKL. How should I make it with MKL, should I add `--config=mkl` as below?
https://github.com/FloopCZ/tensorflow_cc/blob/e1ad656883d16f404a5638a218cd197dbfdc0f08/tensorflow_cc/cmake/build_tensorflow.sh.in#L100

**Comment by songmeixu** [comment]
update:
It may be good to compile a shared lib with MKL using current scripts. However, a static lib with MKL would be preferred.

**Comment by FloopCZ** [comment]
Hi, unfortunately, the static build does not use the `build_tensorflow.sh.in` script at all, but instead, it uses [contrib/makefile](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile) project from the official Tensorflow repository (called from [here](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/TensorflowStatic.cmake#L13)). I believe the `contrib/makefile` project does not support MKL and I don't believe it ever will, so I cannot really help you, sorry.
