### ISSUE TITLE
binary vs library issue

### ISSUE THREAD

**Issue by payas** [FloopCZ/tensorflow_cc#16]
Hi men, I have a stupid question, how do you build a static library ?
the standalone binary works great, but  when I try to build a static library I got 
_### "fatal error: tensorflow/core/platform/env.h: No such file or directory"_

 How do you specify the relationship between a static library and the package?

 If I manually include_directories("/usr/local/include/tensorflow/") I got another error:
_### In file included from /usr/local/include/tensorflow/tensorflow/core/lib/core/errors.h:19:0,
                 from /usr/local/include/tensorflow/tensorflow/core/platform/env.h:24,
                 from /home/payas/source/trunk/iadl_model/iadlmodel.cc:1:
/usr/local/include/tensorflow/tensorflow/core/lib/core/status.h:22:53: fatal error: tensorflow/core/lib/core/error_codes.pb.h: No such file or directory
compilation terminated._

**Comment by FloopCZ** [comment]
Hi @payas,

It seems that `tensorflow` is not compiled properly. Has the `make` step finished successfully? Can you remove the `build` folder and try to rebuild the project from scratch?

**Comment by payas** [comment]
I just rm and rebuild all with no error,  standalone binary build and works fine...

tensorflow/core/lib/core/error_codes.pb.h does even exists ?
it's not on my system, now I'm wondering why standalone binary works

make install never copy that file to tensorflow/core/lib/core/

-- Up-to-date: /usr/local/include/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/lib/core/error_codes.pb.h
-- Up-to-date: /usr/local/include/tensorflow/tensorflow/contrib/makefile/gen/proto/tensorflow/core/lib/core/error_codes.pb.h

 Im pretty lost

**Comment by payas** [comment]
I just figure out

find_package(TensorflowCC REQUIRED )
ADD_LIBRARY(model STATIC
		main.cc)
target_link_libraries(model TensorflowCC::Static) <<<<<----- THIS WAS MISSING

sorryyyyyyy!

**Comment by FloopCZ** [comment]
Yes, that is necessary, glad you solved it. :-)
