### ISSUE TITLE
[feature request] versioning

### ISSUE THREAD

**Issue by galeone** [FloopCZ/tensorflow_cc#160]
Hi @FloopCZ,

Do you think it will be possible to start versioning the tensorflow_cc releases with the same tensorflow release number?

In this way, it will be possible to install the correct tensorflow_cc version, with the correct dependencies being sure that everything is at the correct version.
This will help a lot in the docker images since you can just build tensorflow_cc:1.12 tensorflow_cc:1.13 and so on, making the docker images ready to be used in every scenario (and no more problems with the CUDA version that mismatch, for example).

Thanks!

**Comment by FloopCZ** [comment]
Hi, the project is already versioned according to the TensorFlow version in use, see the [releases](https://github.com/FloopCZ/tensorflow_cc/releases). Maybe I don't understand your question. :-)

**Comment by galeone** [comment]
I can see the versioning of the project, but I can't see the versioning of the docker images.
e.g. what should I do to pull from docker hub the archlinux image that uses tensorflow 1.10?
Looking here https://hub.docker.com/r/floopcz/tensorflow_cc/tags I only see 5 tags, but not a tag for each version (and for each image).

**Comment by FloopCZ** [comment]
I see. I will try to take a look at it in the coming weeks (hopefully not months). :-)
