### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by hellbago** [FloopCZ/tensorflow_cc#162]
I'm trying to compile tensorflow_cc using Cuda 9.0, Cudnn 7, bazel 0.16.1, gcc 5.5 on Ubuntu 16.04 64 bit. I'm getting this error during the build procedure:

```
error while parsing .d file: /home/hellbago/.cache/bazel/_bazel_hellbago/7804ee3d380a70b07846419715bd3fec/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/core/kernels/_objs/fake_quant_ops_gpu/fake_quant_ops_gpu.cu.pic.d (No such file or directory)
In file included from /usr/local/cuda-9.0/bin/..//include/host_config.h:50:0,
                 from /usr/local/cuda-9.0/bin/..//include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/local/cuda-9.0/bin/..//include/crt/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  ^~~~~
Target //tensorflow:libtensorflow_cc.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 422.769s, Critical Path: 57.50s
INFO: 1844 processes: 1844 local.
FAILED: Build did NOT complete successfully
```
Is problem related to Cuda version? Any other suggestion? @FloopCZ

**Comment by FloopCZ** [comment]
> unsupported GNU version! gcc versions later than 6 are not supported!

Are you really sure you are using gcc 5.5 ?

**Comment by FloopCZ** [comment]
My suggestion is to update to Ubuntu 18.04 and use newer everything. :-)

**Comment by hellbago** [comment]
> > unsupported GNU version! gcc versions later than 6 are not supported!
> 
> Are you really sure you are using gcc 5.5 ?

Yes i'm sure. I've also tried with gcc-6 but still got the same issue. Now i want to try using cuda 9.2

**Comment by hellbago** [comment]
I forgot to mention that i've checked out the 1.12 version of tensorflow_cc @FloopCZ

**Comment by hellbago** [comment]
With Cuda 9.2 the build procedure was completed successfully. So I suspect the problem is in someway related to Cuda 9.0 @FloopCZ

**Comment by FloopCZ** [comment]
Nice, thanks. :-)
