### ISSUE TITLE
AVX512F issue

### ISSUE THREAD

**Issue by danperrett** [FloopCZ/tensorflow_cc#165]
I have recently run into an issue that wasn't present before on my Server. 
I've had to rebuild a server and have had to redo a lot of builds.
when I run my tensor flow prject now I get this response:
"tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX512F"

How can I switch on the AVX512F when rebuilding this?
Thanks.

**Comment by FloopCZ** [comment]
Hi, you can `export CC_OPT_FLAGS="-march=native"` before you run the build. Afterwards, the compiler should use all the available instructions and optimizations.

**Comment by danperrett** [comment]
I found the issue, it was just a missing model.pb file, just getting confused by the error it spouted.
Thanks.
