### ISSUE TITLE
libtensorflow_framework.so?

### ISSUE THREAD

**Issue by dec1** [FloopCZ/tensorflow_cc#166]
Hello.

Id like to be able to use tensorflow c++ api with gpu support.

I did:

>  docker run --runtime=nvidia -it floopcz/tensorflow_cc:ubuntu-shared-cuda /bin/bash

and see that the (pre)built binaries seem to be here:

      /usr/local/lib/tensorflow_cc/ 
           libprotobuf.a  libtensorflow_cc.so

and the header files here:

     /usr/local/include/tensorflow/tensorflow/
          core/public/version.h

My understanding is that libtensorflow_cc is the c++ api that sits on top of the core library libtensorflow_framework? So we should need libtensorflow_framework.so as well?

Thanks in advance.

**Comment by FloopCZ** [comment]
Hi @dec1 , the shared version is set to a `monolithic` build type (see [here](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/build_tensorflow.sh.in#L100)), so the `libtensorflow_framework` and `libtensorflow_cc` should be both in a single library.

**Comment by dec1** [comment]
Ok. Thanks very much for clearing that up.
