### ISSUE TITLE
creating "install" from docker container

### ISSUE THREAD

**Issue by dec1** [FloopCZ/tensorflow_cc#167]
Hello.

I did:

    docker run --runtime=nvidia -it floopcz/tensorflow_cc:ubuntu-shared-cuda /bin/bash

and see that the (pre)built binaries seem to be here:
```

  /usr/local/lib/tensorflow_cc/ 
       libprotobuf.a  libtensorflow_cc.so
```

and the header files here:

```
 /usr/local/include/tensorflow/tensorflow/
      core/public/version.h
```

So `lib/tensorflow_cc` and `include/tensorflow/tensorflow` should be copied (out of the docker container), and are all thats needed to create an "install" (dir) for any c++ projects that want to use tensorflow? Is there an installation script (even one that only operates inside the docker container) that automatically pulls out just what clients need and leave behind the rest,  that automates this (and will be updated automatically should the paths/contents etc change in future)? 

Best Wishes and
Thanks in advance.

**Comment by FloopCZ** [comment]
This is basically what `make install` does - it installs the required headers and libraries to the OS. There is a bit more that needs to be copied though, see [here](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/CMakeLists.txt#L69).
