### ISSUE TITLE
How to know the version of an installed tensorflow_cc?

### ISSUE THREAD

**Issue by szm2015** [FloopCZ/tensorflow_cc#168]
Hi,

Suppose that tensorflow_cc is installed on a system, how can I know what version it is? I know how to get TensorFlow version in python, but I don't know how can I do it for c++.

Thank you.

**Comment by FloopCZ** [comment]
Hi, you can retrieve the version from cmake. Try:
```
cat /usr/local/lib/cmake/TensorflowCC/TensorflowCCConfigVersion.cmake | grep ^set\(PACKAGE_VERSION
```
