### ISSUE TITLE
best way to test the tensorflow build

### ISSUE THREAD

**Issue by dec1** [FloopCZ/tensorflow_cc#170]
Hello.

Once tensorflow is built. Is there a way to test this build? ie does tensorflow come with a suite of unit tests and how can one best run them from your docker containers?

Following the answer eg [here](https://stackoverflow.com/questions/34204551/run-tensorflow-unit-tests), I tried as below, but without success.

```
root@43fcf8c53559:/tensorflow_cc/tensorflow_cc/build# bazel test -c opt --config=cuda //tensorflow/...
ERROR: The 'test' command is only supported from within a workspace.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: 11a11dae-a53c-4a4b-b537-1b7c672a6183
```
Thanks in advance.

**Comment by FloopCZ** [comment]
Hi, no, the meta files from the bazel build are already removed in the docker image. The only way to test it is to run the example from this repo (that is, however, always tried before the image is pushed to the docker hub), but of course, that might not be sufficient for you. If you need to run the full test suite, you can build the images yourself (from the dockerfiles in this repo) and run the tests just before the bazel is shut down (i.e. [here](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/build_tensorflow.sh.in#L102)).
