### ISSUE TITLE
cmake _INCLUDE_DIRS variable?

### ISSUE THREAD

**Issue by brianthelion** [FloopCZ/tensorflow_cc#171]
Sorry, my `cmake`-fu is weak here. I see that  `TensorflowCC_Shared_FOUND` is used in the example

https://github.com/FloopCZ/tensorflow_cc/blob/419eb9d9d34575b05e80e0e81aa67f5fa75a4fc7/example/CMakeLists.txt#L6

but I can't seem to find any other helpful `cmake` variables. In particular, I'd like to have access to the API header files in my project `CMakeLists.txt`. What's your naming convention there?

**Comment by FloopCZ** [comment]
Hi, there is no custom naming convention, we use [cmake packages](
https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html) on [this line](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/CMakeLists.txt#L170), so you can use all the variables mentioned in the *cmake packages* docs.
