### ISSUE TITLE
tensorflow_framework

### ISSUE THREAD

**Issue by samhodge** [FloopCZ/tensorflow_cc#173]
Is it possible to make libtensorflow_framework.a?

I have a projects that is dynamically linked to libtensorflow_cc.so and libtensorflow_framework.so

I would like this project to be statically linked.

I have done this before on Windows under TF 1.6 but your systems seems more elegant.

I need to release on Windows Mac and Linux all statically linked for CUDA 9, CUDA 10 and CPU only if possible.

Currently I have the system working dynamically linked using bazel but for reasons now I need it to be statically linked.

**Comment by FloopCZ** [comment]
Hi, this project uses monolithic build, so there is just `libtensorflow_cc` and the `libtensorflow_framework` is integrated inside. But that should not matter for you as you want a static build anyway. Have you tried the `Static library` approach as described in section `3)` in `README.md`?

**Comment by samhodge** [comment]
I tried the static library approach worked well under Linux, need to complete the building into the app under Linux. Seems to be just using the makefile.

**Comment by samhodge** [comment]
@FloopCZ 

Can you advise on this?

https://stackoverflow.com/questions/56013508/libtensorflow-core-a-missing-symbols-tensorflowportinitmainchar-const-in

**Comment by samhodge** [comment]
best look here for the solution

https://github.com/tensorflow/tensorflow/issues/28388
