### ISSUE TITLE
building without tensorRT

### ISSUE THREAD

**Issue by omerbrandis** [FloopCZ/tensorflow_cc#174]
Hello.

I'm trying to build tensorflow_cc v 1.6 on ubuntu 16.04 using gpu 
using the command cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON .. 
( I've successfully performed this in the past a few times).

this time, i'm doing it on a pre-built  nvidia docker container "nvcr.io/nvidia/tensorflow:18.04-py2
" that already has a lot of things installed , like tf-python v1.7,,,

while building tensorflow_cc , i am asked 
"Please specify the location where TensorRT is installed. [Default is /usr/lib/x86_64-linux-gnu]:"

**this is new to me.
in the past this was not required.**

never the less, the used docker image has tensorRT 4.0.4 installed, so i pressed enter ...
but the build failed with:
"Cuda Configuration Error: TensorRT library version detected from /usr/include/x86_64-linux-gnu/NvInfer.h (4		//!<.0		//!<.4		//!<) does not match TF_TENSORRT_VERSION (4.0.4). To fix this rerun configure again."

i removed the installation of TensorRT ( apt-get purge "libnvinfer*")
now make still asks about the installation directory for tensorRT , but now i don't have it installed... so the build fails again.

**what i'm asking is how to build tensorflow_cc v1.6 without tensortRT.
( its not a cmake parameter )**

the error msg also has :
Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See tools/bazel.rc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=tensorrt    	# Build with TensorRT support.

suggesting that this is caused by some sort of bazel configuration.
but build_tensorflow.sh contains
"bazel build -c opt \
            $cuda_config_opts \
            --config=monolithic \
            tensorflow:libtensorflow_cc.so"

please advise,
omer.

**Comment by FloopCZ** [comment]
Hi, this really should not happen, TensorRT is disabled by default:
https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/build_tensorflow.sh.in#L15
Are you sure you have a clean and the most recent version of this repository?

**Comment by omerbrandis** [comment]
i use the following cmd to get tf_cc 1.6 :

wget https://github.com/FloopCZ/tensorflow_cc/archive/v1.6.0.zip

i then 
2) $ unzip 1.6.0.zip

3) $ cd 1.6.0/tensorflow_cc/

4) $ mkdir build && cd build

5) $ cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON ..

6) make.

thanks,
Omer.

**Comment by FloopCZ** [comment]
TF 1.6 is outdated not supported anymore. I suggest to use the latest TF 1.13.1 as there have been many bugfixes since then.
