### ISSUE TITLE
why is ubntu18.4 a requirement as of tf_cc v1.8 ?

### ISSUE THREAD

**Issue by omerbrandis** [FloopCZ/tensorflow_cc#175]
hello, 

I would like to install the latest versions of tf_cc on ubuntu 16.04,
but have noticed that as of v1.8 the ubuntu 18.04 is required.
( while this is not required by the save versions of tensorflow_"python".

also noticed that the cuda requirement is just 9.2 , which is supported on ubuntu 16.04.

can you please share why ubuntu 18 is required as of tf_cc 1.8 ? 
is this a "hard" requirement ? 
or simply that tf_cc v1.8 and above were not tested on 16.04 ?

thanks,
Omer.

**Comment by FloopCZ** [comment]
Only Ubuntu 18.04 is tested. If you manage to get the right versions of required packages and compiler, it may work on Ubuntu 16.04 as well.
