### ISSUE TITLE
tensorflow_cc with tensorflow 1.7

### ISSUE THREAD

**Issue by yaira24** [FloopCZ/tensorflow_cc#176]
Hi first of all great work with this repository.
I used this repository with tensorflow 1.7 version with cuda 9.0 
it is possible to get this repository tag to checkout that I can return to a version that has this configuration.  I downloaded this repository at 30/4/2018 and I need it to another computer

**Comment by FloopCZ** [comment]
Hi, sorry, I really have no idea what is the working version with this release. I recommend testing the latest version and passing:
```
cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON -DTENSORFLOW_TAG="v1.7.0" ..
```
But I would not expect such an old version to work.

**Comment by yaira24** [comment]
thanks, I find the old copy of the version,  I recompile and it works thanks for the help.
maybe in the fouter, you can tag your version with the Cuda and TF version so how need spasific version can have that.  and again great work with this repository
