### ISSUE TITLE
How to disable GPU support for the shared library build?

### ISSUE THREAD

**Issue by EternalSaga** [FloopCZ/tensorflow_cc#178]
I didn't find any instuctions about how to build a CPU only library.

**Comment by Youw** [comment]
Have you tried `cmake -DALLOW_CUDA=OFF <other args...>` when build? Try `cmake-gui` - it will show you all the options available

**Comment by FloopCZ** [comment]
If this did not work for you, feel free to reopen the issue. Thank you @Youw .
