### ISSUE TITLE
Protobuf Issue

### ISSUE THREAD

**Issue by yshen92** [FloopCZ/tensorflow_cc#19]
Hi,

Thank you a lot for the awesome work! @FloopCZ 
I have managed to compile my code in C++ using cmake. 
However am getting this error:
`[libprotobuf FATAL external/protobuf/src/google/protobuf/stubs/common.cc:78] This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.3.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-ui6vjS/mir-0.26.3+16.04.20170605/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.3.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-ui6vjS/mir-0.26.3+16.04.20170605/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)
`

I am not very familiar to protobuf. 
Can you kindly advise how should I work around this?
And may I know the version of the protobuf used in your tensorflow_cc?

Appreciated.

**Comment by yshen92** [comment]
Issue solved. Problem was with OpenCV. TQ

**Comment by Edwardmark** [comment]
@yshen92 how you solve it? by downgrade the tensorflow protobuf version or by upgrading the opencv protobuf version?

**Comment by Edwardmark** [comment]
this is a serious question, I am really confused.

**Comment by yshen92** [comment]
@Edwardmark the easiest solution would be to consider rebuilding opencv without protobuf.

**Comment by FloopCZ** [comment]
@Edwardmark You may want to play with #35 (`configurable-protobuf` branch) if it helps you solve the issue.
