### ISSUE TITLE
Passing Options to Bazel Build

### ISSUE THREAD

**Issue by dtsmith2001** [FloopCZ/tensorflow_cc#190]
I would like to know how I can modify CMakeFile.txt to include bazel options

- `--config=v2`
- `--local_ram_resources=2048`
- `--jobs=1`

See https://www.tensorflow.org/install/source#bazel_build_options and, more specifically, https://docs.bazel.build/versions/master/command-line-reference.html#flag--local_resources

Given enough info, I can make this enhancement and send you a PR.

**Comment by FloopCZ** [comment]
Hi, sure, you can do that. It would be sufficient to dedicate an environmental variable similar to `CC_OPT_FLAGS` here:
https://github.com/FloopCZ/tensorflow_cc/blob/775609e9ed045ef8bfbbfb0b02b3c5af89ed5d38/tensorflow_cc/cmake/build_tensorflow.sh.in#L10
And use it here:
https://github.com/FloopCZ/tensorflow_cc/blob/775609e9ed045ef8bfbbfb0b02b3c5af89ed5d38/tensorflow_cc/cmake/build_tensorflow.sh.in#L78

**Comment by dtsmith2001** [comment]
> Hi, sure, you can do that. It would be sufficient to dedicate an environmental variable similar to `CC_OPT_FLAGS` here:
> 
> https://github.com/FloopCZ/tensorflow_cc/blob/775609e9ed045ef8bfbbfb0b02b3c5af89ed5d38/tensorflow_cc/cmake/build_tensorflow.sh.in#L10
> 
> And use it here:
> 
> https://github.com/FloopCZ/tensorflow_cc/blob/775609e9ed045ef8bfbbfb0b02b3c5af89ed5d38/tensorflow_cc/cmake/build_tensorflow.sh.in#L78

I am not sure when I can get to this, but I need it. I hope to have something for you by next week.

**Comment by dtsmith2001** [comment]
Thanks sorry I will work on it this week.

**Comment by dtsmith2001** [comment]
I'm testing building the Docker container for Ubuntu right now, but I see this message

```
CMake Warning:
  Manually-specified variables were not used by the project:

    CC_OPT_FLAGS
```

I've seen this before, but it's an option in [build_tensorflow.sh.in](https://github.com/FloopCZ/tensorflow_cc/blob/775609e9ed045ef8bfbbfb0b02b3c5af89ed5d38/tensorflow_cc/cmake/build_tensorflow.sh.in#L10). I don't think this variable can be specified manually.

You can review [my changes](https://github.com/dtsmith2001/tensorflow_cc/tree/ea0f607a1d27637aec7e5bd69b551acb5d34c0e4).

Thanks @FloopCZ for the assistance.

**Comment by dtsmith2001** [comment]
I found a few bugs so I'm working on this right now. And I'm breaking up the added Bazel line

```bash
export BAZEL_OPT_FLAGS=${BAZEL_OPT_FLAGS:-"--jobs=1 --local_ram_resources=2048 --copt=-mfpmath=both --copt=-msse4.2 --copt=\"-march=native\""}
```

into separate variables for maximum flexibility.

**Comment by FloopCZ** [comment]
> I've seen this before, but it's an option in build_tensorflow.sh.in. I don't think this variable can be specified manually.

The `build_tensorflow.sh.in` can use variables defined in `CMakeLists.txt` even as a parameter. Take a look e.g. at how `ALLOW_CUDA` option is propagated through:
https://github.com/dtsmith2001/tensorflow_cc/blob/ea0f607a1d27637aec7e5bd69b551acb5d34c0e4/tensorflow_cc/CMakeLists.txt#L11

**Comment by FloopCZ** [comment]
Now there is a support for local resources setting. Try e.g.,
`cmake -DLOCAL_RAM_RESOURCES=2048 -DLOCAL_CPU_RESOURCES=4 ..`
