### ISSUE TITLE
build failed at downloading eigen from bitbucket

### ISSUE THREAD

**Issue by hellbago** [FloopCZ/tensorflow_cc#192]
Right now the build process stops at:
```
downloading https://bitbucket.org/eigen/eigen/get/49177915a14a.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
Even with wget I cannot download the link due to authentication problem @FloopCZ

**Comment by FloopCZ** [comment]
Yes, `eigen` is being migrated today, see the [news](http://eigen.tuxfamily.org/index.php?title=News:Migration_to_GitLab.com_scheduled_on_the_December_4th). Let's see what we can do when they finish the migration.

**Comment by dtsmith2001** [comment]
The GitHub mirror for Eigen is directing to https://gitlab.com/libeigen/eigen. The GitHub repository is to be deleted Real Soon Now.

The GitLab repository is apparently not created yet as of 2:56 PM EDT.

**Comment by dtsmith2001** [comment]
@FloopCZ the Eigen repository at GitLab is now available.

https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz

**Comment by FloopCZ** [comment]
The migration is complete - it should be working again.
