### ISSUE TITLE
subsequent build command fails

### ISSUE THREAD

**Issue by Youw** [FloopCZ/tensorflow_cc#195]
The work flow:
1) Clone tensorflow_cc master (or v1.15.0 - same result right now);
2) Configure with CMake (tested on Ubuntu 18.04 with Make Generator, CUDA support);
3) Build (by either `cmake --build ...` or `make` directly;

The project being built successfully.

4) Build for the second time (call `make`):
The build is failing on patch step:
```
[ 56%] Performing configure step for 'tensorflow_shared'
v1.15.0-Rename-gettid-functions.patch:25: trailing whitespace.
 
v1.15.0-Rename-gettid-functions.patch:28: trailing whitespace.
 
v1.15.0-Rename-gettid-functions.patch:37: trailing whitespace.
 
v1.15.0-Rename-gettid-functions.patch:47: trailing whitespace.
 
v1.15.0-Rename-gettid-functions.patch:50: trailing whitespace.
 
error: third_party/Rename-gettid-functions.patch: already exists in working directory
CMakeFiles/tensorflow_shared.dir/build.make:107: recipe for target 'tensorflow-stamp/tensorflow_shared-configure' failed
```

---
A workaround:
```sh
cd tensorflow_cc/tensorflow
git reset HEAD
git checkout .
rm third_party/Rename-gettid-functions.patch v1.15.0-Rename-gettid-functions.patch v1.15.0-workspace.bzl.patch
```

Run build again: it succeed.

---
Would be nice to be able to run build again without manual steps.

**Comment by FloopCZ** [comment]
Hi, this is strange, are you sure the first `make` finished successfully? Because if it succeeds, it should not rebuild `tensorflow`. I have just tried and it seems to work just fine:
```
...
[100%] Completed 'tensorflow_shared'
[100%] Built target tensorflow_shared
[ 50%] Built target tensorflow_base
[100%] Built target tensorflow_shared
[ 50%] Built target tensorflow_base
[100%] Built target tensorflow_shared
```

**Comment by Youw** [comment]
Ah, no, it wasn't success - that's one of the cases: I started the build, and it failed, because one of the dependencies was missing. I've installed it and `make -j` again.

The other case I was playing with:
- successfully build CPU-only;
- configure with GPU support (with different install prefix);
- (try to) build again;

In any of the above I don't really want to do full clean rebuild - it takes time for things like `git clone` which I'd rather reuse.

**Comment by jasjuang** [comment]
Ran into the same problem and #196 doesn't seem to solve it for me

**Comment by jasjuang** [comment]
@Youw I deleted the patches in the build folder and it doesn't seem to solve the problem. After `make -j` it still shows the same error.

**Comment by Youw** [comment]
> I deleted the patches

how exactly did you deleted those patches? by (exactly) a commands, described by my in the `workaround` section?

**Comment by jasjuang** [comment]
@Youw I wasn't able to use your exact command because there is no `third_party` folder, the patches are in a `patches` folder instead. 

At least if I clear the build folder and do a fresh build it's able to get past that problem, however, I ran into the below error

```
tensorflow/contrib/makefile/downloads/nsync/builds/default.linux.c++11/nsync.a
CUDA support enabled
find: ‘/etc/ssl/private’: Permission denied
find: ‘/etc/polkit-1/localauthority’: Permission denied
find: ‘/etc/sudoers.d’: Permission denied
find: ‘/etc/docker’: Permission denied
find: ‘/proc/tty/driver’: Permission denied
find: ‘/proc/1/task/1/fd’: Permission denied
find: ‘/proc/1/task/1/fdinfo’: Permission denied
find: ‘/proc/1/task/1/ns’: Permission denied
find: ‘/proc/1/fd’: Permission denied
find: ‘/proc/1/map_files’: Permission denied
find: ‘/proc/1/fdinfo’: Permission denied
find: ‘/proc/1/ns’: Permission denied
find: ‘/proc/2/task/2/fd’: Permission denied
find: ‘/proc/2/task/2/fdinfo’: Permission denied
find: ‘/proc/2/task/2/ns’: Permission denied
find: ‘/proc/2/fd’: Permission denied
...
```

**Comment by Youw** [comment]
`cd tensorflow_cc/tensorflow` - note, that this is a CMake **build** directory

**Comment by jasjuang** [comment]
I was able to get past the permission problem by using `sudo make`, even though I don't think I should need to, the next problem I ran into is this

```
You have bazel 2.0.0 installed.
Please downgrade your bazel installation to version 0.26.1 or lower to build TensorFlow!
```

Problem is when I `sudo apt install bazel` tab tab tab, I only have the options below 

```
bazel        bazel-1.0.0  bazel-1.0.1  bazel-1.1.0  bazel-1.2.0  bazel-1.2.1  bazel-2.0.0
```

**Comment by Youw** [comment]
Remove what you've installed from apt, and install manually from here: https://github.com/bazelbuild/bazel/releases?after=0.28.0

**Comment by jasjuang** [comment]
I finally got tensorflow 1.15 to work with bazel 0.26.1, cuda 10.2, and protobuf 3.8.0 while not breaking pytorch. Thanks for the help.

**Comment by buni-rock** [comment]
@jasjuang how did you managed to compile tensorflow 1.15 with cuda 10.2? Everywhere I look, there are only issues/failures on trying to compile these 2 together. I have also tried it and in failed due to some fatbinary errors or so...
Do you have, by chance, a step-by-step description on how did you achieved that?

**Comment by Youw** [comment]
I was able to build it in one try (Ubuntu 18.04):
- `sudo apt update`
- `sudo apt install cuda-10-2 libcudnn7 libcudnn7-dev`
- install bazel 0.26.1
- build master tensorflow_cc
