### ISSUE TITLE
How to build with MKL

### ISSUE THREAD

**Issue by cyrusbehr** [FloopCZ/tensorflow_cc#197]
Hi there,
I am looking to get the best performance possible when running tensorflow on CPU. I would therefore like to link against mkl for the backend blas library.

How can this be done?

**Comment by cyrusbehr** [comment]
After inspecting `build_tensorflow.sh`, it looks like it is already being built with mkl:
```
export TF_NEED_MKL=${TF_NEED_MKL:-1}
export TF_DOWNLOAD_MKL=${TF_DOWNLOAD_MKL:-1}
```

can you confirm that this is indeed the case?

**Comment by FloopCZ** [comment]
Yes, this is the case indeed. MKL is downloaded during the build process.
