### ISSUE TITLE
Way to change protoc version?

### ISSUE THREAD

**Issue by mtee** [FloopCZ/tensorflow_cc#20]
Now this may be a silly question, but how can I change the version of protoc that is used to generate the .pb.h files like
/usr/local/include/tensorflow/bazel-genfiles/tensorflow/core/lib/core/error_codes.pb.h
and 
/usr/local/include/tensorflow/bazel-genfiles/tensorflow/core/framework/graph.pb.h
and the likes? 
Currently it is using the 3.3.0 version of protobuf, but I need the files to be compatible with 2.6 runtime.

**Comment by FloopCZ** [comment]
Currently, `tensorflow_cc` builds protobuf using [tensorflow/contrib/makefile](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile) project, which is supposed to build the right protobuf version for the current tensorflow version. I am not sure whether it is even possible to build TF 1.3.0 to be compatible with protobuf 2.6. If you want to experiment with this, you may try [not to build](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/TensorflowStatic.cmake#L12) protobuf using the `contrib/makefile` project and change [the included directories](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/CMakeLists.txt#L95) and [linked libraries](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/CMakeLists.txt#L95) in the CMakeLists.txt. However, I don't think it is worth the effort.

Are you sure you need this? `protobuf` is currently statically linked in the final `tensorflow_cc` dynamic library, so there should be no need to link to dynamic protobuf at all.
