### ISSUE TITLE
undefined reference to `tflite::DefaultErrorReporter()'

### ISSUE THREAD

**Issue by ashishmagar600** [FloopCZ/tensorflow_cc#202]
I successfully built tensorflow_cc on Ubuntu 16.04 with a static build.

I was testing a small code I took from tflite guide:

$> cat test1.cpp

#include < cstdio >
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model.h"

using namespace tflite;

int main(int argc, char* argv[]) {
  if (argc != 2) {
    fprintf(stderr, "minimal <tflite model>\n");
    return 1;
  }
  const char* filename = argv[1];

  std::unique_ptr<tflite::FlatBufferModel> model =
      tflite::FlatBufferModel::BuildFromFile(filename);
  return 0;
}

I am getting this error:

[ 50%] Building CXX object CMakeFiles/example.dir/example.cpp.o
[100%] Linking CXX executable example
CMakeFiles/example.dir/example.cpp.o: In function `main':
example.cpp:(.text+0x57): undefined reference to `tflite::DefaultErrorReporter()'
example.cpp:(.text+0x6d): undefined reference to `tflite::FlatBufferModel::BuildFromFile(char const*, tflite::ErrorReporter*)'
CMakeFiles/example.dir/example.cpp.o: In function `std::default_delete<tflite::FlatBufferModel>::operator()(tflite::FlatBufferModel*) const':
example.cpp:(.text._ZNKSt14default_deleteIN6tflite15FlatBufferModelEEclEPS1_[_ZNKSt14default_deleteIN6tflite15FlatBufferModelEEclEPS1_]+0x1e): undefined reference to `tflite::FlatBufferModel::~FlatBufferModel()'
collect2: error: ld returned 1 exit status
CMakeFiles/example.dir/build.make:85: recipe for target 'example' failed
make[2]: *** [example] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/example.dir/all' failed
make[1]: *** [CMakeFiles/example.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Any suggestions on how to proceed?

**Comment by FloopCZ** [comment]
This project does not actually build TF Lite library, at least not in the static build. You need to follow the TF Lite build guide to do that, e.g., https://www.tensorflow.org/lite/guide/build_rpi.

**Comment by ashishmagar600** [comment]
This issue is answered here:
[link](https://github.com/tensorflow/tensorflow/issues/36661)

I had to do build and link separately.
Also, using -ltensorflowlite after the object file.

Thank you
