### ISSUE TITLE
Tensorflow 2.1.0 support

### ISSUE THREAD

**Issue by m4ce** [FloopCZ/tensorflow_cc#203]
Is there any plan to support 2.1.x?

**Comment by FloopCZ** [comment]
Well, now that `contrib` is gone in 2.*, we would have to drop support for static build because it stands heavily on `contrib/makefile`. Maybe it is worth it, maybe not, I am still not sure. Any opinions?

**Comment by rbgreenway** [comment]
Definitely worth it.
