### ISSUE TITLE
version 1.14?

### ISSUE THREAD

**Issue by r2dliu** [FloopCZ/tensorflow_cc#206]
There doesn't seem to be a release for version 1.14. I see commits that seem to be related to that version though. Is there a commit hash I can checkout that would be optimal for trying to get this version working? or were there other issues preventing that?

**Comment by FloopCZ** [comment]
Hi, if I remember correctly, there were some issues and I decided to skip directly to `v1.15`. If you really want to try anyway, I suggest to get version v1.15 of this project and use `TENSORFLOW_TAG` parameter of the `CMakeLists.txt` to checkout tensorflow v1.14, but I cannot guarantee it will work for you.

**Comment by r2dliu** [comment]
This was a while ago, but I did get this to work incidentally. Changed the tag and built fine.
