### ISSUE TITLE
build shared library using TensorflowCC::Static

### ISSUE THREAD

**Issue by payas** [FloopCZ/tensorflow_cc#21]
Hello, I'm using the static version of TensorflowCC, it works great when a build a binary, now I'm trying to build a shared library to dlopen() from another binary

 the problem: I can not link it

ADD_LIBRARY(iadlmodel SHARED
		iadlmodel.cc)		
target_link_libraries(iadlmodel TensorflowCC::Static)

ERROR:
/usr/bin/ld: CMakeFiles/iadlmodel.dir/iadlmodel.cc.o: relocation R_X86_64_32 against `_ZTVN4iadl12TrainedModel5ModelE' can not be used when making a shared object; recompile with -fPIC
CMakeFiles/iadlmodel.dir/iadlmodel.cc.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/iadlmodel.dir/build.make:95: recipe for target 'libiadlmodel.so' failed

 is this posible ?

**Comment by FloopCZ** [comment]
Hi @payas, although it is strange, it seems that your library is not build with position independent code. Try to add:
```cmake
set_property(TARGET iadlmodel PROPERTY POSITION_INDEPENDENT_CODE ON)
```
to your CMakeLists.txt.

**Comment by payas** [comment]
oh god.. I did put the POSITION_INDEPENDENT_CODE, I just forgot the "ON"
it's perfect now
-rwxrwxr-x 1 payas payas 78967360 Sep 26 12:32 libiadlmodel.so*

 thank you very much!
