### ISSUE TITLE
Anywhere to download prebuild version? for mac os?

### ISSUE THREAD

**Issue by cxwx** [FloopCZ/tensorflow_cc#211]

**Comment by FloopCZ** [comment]
There is only the docker image version available for download so far. Unfortunately, there has not been done much about packaging (see https://github.com/FloopCZ/tensorflow_cc/issues/8) or Mac OS support. So far, the only supported systems are Ubuntu 18.04+ and Arch Linux.

**Comment by cxwx** [comment]
so sadly, it take me 6 hours to compile it on my macbook pro 2015
