### ISSUE TITLE
[Bug] Build success, installation incomplete, tensorflow/core/platform/env.h not found!

### ISSUE THREAD

**Issue by yiakwy-enterprise-roborock** [FloopCZ/tensorflow_cc#213]
#  some files absent in installation directory
I manually donwloaded tensorflow and modified cmake/TensorFlowBase.cmake to proceed to compilation. Everything goes well now after make and install.

However when I link the library to an executable using the example,  cmake is able to find Tensorflow in /usr/local/include/tensorflow", but cannot see "tensorflow/core/platform/env.h"

There are two problems after I studied the output files:

1) installation directory is actually "/usr/local/tensorflow/bazel-bin/tensorflow/core/platform"
2) there is no header files inside that directory.
3) env.h actually relies inside "bazel-tensorflow" but our CMakeList.txt does not record that.

My tensorflow version is 2.1.0. I guess installation is broken since CMakefile.txt does not write anything about it, as a result which the installation is successful but indeed incomplete!

# The project install generated sources files by bazel incorrectly

For details about how to resolve the problem, see this project https://github.com/cjweeks/tensorflow-cmake

# previous issue considered a solution to be merged:

https://github.com/FloopCZ/tensorflow_cc/issues/212

**Comment by yiakwy-enterprise-roborock** [comment]
@FloopCZ I have resolved the problem by manually copying files into "/usr/local/" as described in "tensorflow_cmake" project as I did one year ago.

Now I am facing a new problem and I invited you to help to solve:

https://github.com/tensorflow/tensorflow/issues/38237

**Comment by hongson23** [comment]
Hi @yiakwy-enterprise-roborock 

I have same issue, "cannot see "tensorflow/core/platform/env.h", Can you detail your resolve the problem by manually copying files into "/usr/local/"?
