### ISSUE TITLE
Using this for cross-compilation

### ISSUE THREAD

**Issue by sillick-rfa** [FloopCZ/tensorflow_cc#217]
I've been able to successfully compile this for both X86_64 and for ARM64/aarch64. Now I would like to cross compile my application for ARM64 from within my X86_64 environment.

I have a sysroot installed at /mnt with my ARM64 environment and the ARM64 version I compiled of TensorflowCC installed

I am using crossbuild-essential-arm64 to cross compile.

Here is my Toolchain file in CMake. I call -DCMAKE_TOOLCHAIN_FILE=this_file.cmake when I do the cmake command in my app.

```
# this one is important 
SET(CMAKE_SYSTEM_NAME Linux) 
#this one not so much 
SET(CMAKE_SYSTEM_VERSION 1) 
 
SET(CMAKE_C_COMPILER_WORKS 1) 
SET(CMAKE_CXX_COMPILER_WORKS 1) 
# specify the cross compiler 
SET(CMAKE_C_COMPILER "/usr/bin/aarch64-linux-gnu-gcc") 
SET(CMAKE_CXX_COMPILER "/usr/bin/aarch64-linux-gnu-g++") 
 
 
SET(PROJECT_PROCESSOR "aarch64") 
SET(CMAKE_SYSTEM_PROCESSOR "aarch64") 
include_directories(SYSTEM "/mnt/usr/include" "/mnt/usr/local/include") 
# where is the target environment 
SET(CMAKE_FIND_ROOT_PATH "/mnt") 
SET(CMAKE_SYSROOT /mnt) 
 
# search for programs in the build host directories 
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER) 
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)  
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY) 
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY) 
# end of the file

```

How would I change the TensorflowCCTargets.cmake and/or TensorflowCCConfig.cmake file to use the different sysroot?

**Comment by sillick-rfa** [comment]
Possibly this needs to be in your TensorflowCCConfig.cmake.in file?

# Search packages for host system instead of packages for target system.
# in case of cross compilation this macro should be defined by toolchain file
if(NOT COMMAND find_host_package)
    macro(find_host_package)
        find_package(${ARGN})
    endmacro()
endif()
if(NOT COMMAND find_host_program)
    macro(find_host_program)
        find_program(${ARGN})
    endmacro()
endif()

**Comment by FloopCZ** [comment]
Well, I am actually quite surprised you managed to compile for ARM64/aarch64 at all. :slightly_smiling_face: 
Did the snippet you provided help you?

**Comment by sillick-rfa** [comment]
It did not, but I did figure out what's going on.

In your CMakeLists.txt file.

```
target_include_directories(
  tensorflow_cc INTERFACE
  "${CMAKE_INSTALL_PREFIX}/include/tensorflow/bazel-bin/tensorflow/include"
  "${CMAKE_INSTALL_PREFIX}/include/tensorflow/bazel-bin/tensorflow/include/src"
)
target_link_libraries(
  tensorflow_cc INTERFACE
  "${CMAKE_INSTALL_PREFIX}/lib/libtensorflow_cc.so.${PROJECT_VERSION_MAJOR}"
  dl pthread
)
```

This isn't very portable. That hard codes the TensorflowCCTargets.cmake that is generated to your install directory, because that's what CMAKE_INSTAL_PREFIX is. May I recommend you make it more relocatable by using the strategies laid out here?

https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#creating-relocatable-packages
