### ISSUE TITLE
protobuf link error with floopcz/tensorflow_cc:ubuntu-2.2.0

### ISSUE THREAD

**Issue by jimlloyd** [FloopCZ/tensorflow_cc#219]
I'm trying to upgrade my project to tensorflow 2.2. My project uses `tensorflow::LoadSavedModel` provided by `tensorflow/cc/saved_model/loader.h`. With 2.2 I get this link error:

```
/usr/bin/ld: lib/libcore_lib.a(Predictor.cpp.o): in function `tensorflow::SavedModelBundle::GetSignatures[abi:cxx11]() const':
Predictor.cpp:(.text._ZNK10tensorflow16SavedModelBundle13GetSignaturesB5cxx11Ev[_ZNK10tensorflow16SavedModelBundle13GetSignaturesB5cxx11Ev]+0x10): undefined reference to `google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField() const'
```

Previously I was able to build `protobuf v3.8.0` and install it as a system library. I initially tried that and ran into this error. It seems that tensorflow 2.2rc4 is still using v3.8.0, although with a patch. 

https://github.com/tensorflow/tensorflow/blob/r2.2/tensorflow/workspace.bzl

`    # 310ba5ee72661c081129eb878c1bbcec936b20f0 is based on 3.8.0 with a fix for protobuf.bzl.`

So I tried installing protobuf using the same tarball, but I see the same link error.

Have you been able to use `LoadSavedModel` with tensorflow 2.2? Do you have any suggestions for how I could resolve this problem?

**Comment by jappoz** [comment]
I am having the same issue.
Interestingly enough, the error disappears if I use SavedModelBundleLite instead of SavedModelBundle. 

Did someone find a solution for this?

**Comment by jappoz** [comment]
I found a solution [here](https://github.com/tensorflow/tensorflow/issues/40004).
The problem seems to be tensorflow not exporting protobuf symbols.

**Comment by jimlloyd** [comment]
I have confirmed that using `SavedModelBundleLite` fixes the link error in my app. That interface is now documented as the preferred interface in new code:

```
// A version of SavedModelBundle that avoids storing a potentially large
// MetaGraphDef. Prefer to use SavedModelBundleLite in new code.
```

I think that means it is acceptable to close this issue.

Thanks @jappoz!

**Comment by michaelnguyen11** [comment]
I think the problem is that author removed "protobuf" in cmake. See this commit : https://github.com/FloopCZ/tensorflow_cc/commit/c1520a0212b108eaae1ce7f47231910ce9f91845

Reverted this commit and I could use the LoadSavedBundle function normally.

**Comment by xiandong79** [comment]
@FloopCZ do you think  See this commit : https://github.com/FloopCZ/tensorflow_cc/commit/c1520a0212b108eaae1ce7f47231910ce9f91845 should be reverted or not?

**Comment by FloopCZ** [comment]
Hi @xiandong79, feel free to try #246 .
