### ISSUE TITLE
Installing without sudo

### ISSUE THREAD

**Issue by mfobert** [FloopCZ/tensorflow_cc#222]
Thanks for the library!

I am attempting to use this to run on some supercomputers, but don't have root access! I was wondering if you have a suggestion for how to run the install portion without sudo and still get the TensorflowCC build targets?

Thanks,
Mark

**Comment by FloopCZ** [comment]
Hi, you should be able to use e.g., `-DCMAKE_INSTALL_PREFIX=~/.local` option for `cmake` command and register the `~/.local` folder hierarchy in your `LIBRARY_PATH` etc. (see lines 10-14 [here](https://github.com/FloopCZ/linux-environment/blob/master/_zprofile#L10)).
