### ISSUE TITLE
Uninstall completely before changing TF version?

### ISSUE THREAD

**Issue by mrdaliri** [FloopCZ/tensorflow_cc#226]
Hi,

For the first time, I compiled tensorflow_cc with TF 1.15 and then run `sudo make install` to install shared libraries. Now I'm switching to TF 2.2. Is there a way to completely remove previously installed libraries and then install the new one?

**Comment by FloopCZ** [comment]
Unfortunately,  CMake does not support `make uninstall` target by default. Something like
```
xargs rm < install_manifest.txt
```
executed from the `build` folder may or may not work though.
