### ISSUE TITLE
gcc is killed during build because of RAM limitation

### ISSUE THREAD

**Issue by mrdaliri** [FloopCZ/tensorflow_cc#227]
It seems to be a common issue while building Tensorflow from source:

Here is a quote from [the official documentation](https://www.tensorflow.org/install/source#bazel_build_options):
    
> Building TensorFlow from source can use a lot of RAM. If your system is memory-constrained, limit Bazel's RAM usage with: `--local_ram_resources=2048`.

Maybe we can have a flag to configure this for Bazel? I can submit a PR if @FloopCZ agrees.

**Comment by FloopCZ** [comment]
Hi, sure, we can have a flag for that, feel free to make a PR. :slightly_smiling_face:
