### ISSUE TITLE
Issued find over the root of my filesystem??

### ISSUE THREAD

**Issue by jeremysalwen** [FloopCZ/tensorflow_cc#229]
I followed the most basic instructions...

```
git clone https://github.com/FloopCZ/tensorflow_cc.git
cd tensorflow_cc/tensorflow_cc
mkdir build
cd build
cmake ..
export CC_OPT_FLAGS="-march=native"
make -j7
```
After a bit I see it is executing find over my root filesystem??

find: ‘/etc/ssl/private’: Permission denied
find: ‘/proc/21431/task/21431/fdinfo’: Permission denied
...
etc, etc

**Comment by FloopCZ** [comment]
Hi, thanks for reporting, that is disturbing. The only `find` I can think of is https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/copy_links.sh#L10 and it should not be run on your root fs unless some symlink is pointing to it. Which would be surprising. What is your OS and Bazel version? And do you remember which part of the build did this happen at (e.g., at the very end)?

(note to myself - is `copy_links.sh` still necessary?)

**Comment by jeremysalwen** [comment]
I think this is the source? 

https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/build_tensorflow.sh.in#L61

**Comment by FloopCZ** [comment]
Good catch, totally forgot about this one, should have grepped. See #233 for an improvement.
