### ISSUE TITLE
building and packaging python 

### ISSUE THREAD

**Issue by leslie-wang** [FloopCZ/tensorflow_cc#235]
Thanks for the nice project. It works great!

One more feature request is if you can add python build and package as well. This is because I had some python codes and want to compare the output of python and c++ result for the same result, so as to know C++ code is correct or not. I can install python package from other sources, but it would be fair if everything is from same tensor library.

**Comment by FloopCZ** [comment]
Unfortunately, adding Python to this build would add a significant number of dependencies and it would increase maintenance complexity. Installing TF for Python is well supported and so simple (e.g., PyPI) that I would rather not include it in this project.
