### ISSUE TITLE
Build failed downloading Eigen from Bitbucket

### ISSUE THREAD

**Issue by arainbilal** [FloopCZ/tensorflow_cc#236]
Related issues: #192 
@FloopCZ, The Eigen repository defined in workspace.bzl is using https://bitbucket.org/eigen/eigen/get/49177915a14a.tar.gz, which is not available to build for TFv1.15.0. How can we define it to the Eigen repository at GitLab as you have mentioned in #192. Thanks for your help

**Comment by fakhamatia** [comment]
@arainbilal How fix this problem for 1.15?

**Comment by minfenghong** [comment]
> @arainbilal How fix this problem for 1.15?

Hi,
I modified tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/contrib/makefile/download_dependencies.sh

#EIGEN_URL="$(grep -o 'http.*bitbucket.org/eigen/eigen/get/.*tar\.gz' "${BZL_FILE_PATH}" | grep -v mirror.bazel | head -n1)"
EIGEN_URL="https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz"

And success to build 1.13.1. Not sure if it can work in 1.15.

**Comment by xiandong79** [comment]
@arainbilal could you illustrate more?

**Comment by mightbxg** [comment]
For those who want to build 1.15.0 docker, open `tensorflow_cc/cmake/TensorflowBase.cmake`, add this line to L23 (before `COMMAND tensorflow/contrib/makefile/download_dependencies.sh`):
```sh
COMMAND sed -i "s#EIGEN_URL=.*#EIGEN_URL=\"https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz\"#g" tensorflow/contrib/makefile/download_dependencies.sh
```
