### ISSUE TITLE
Can't download tensorflow while running make command

### ISSUE THREAD

**Issue by fisakhan** [FloopCZ/tensorflow_cc#239]
After successful execution of "cmake ..", make command fails while downloading some tar.gz files. My operating system is CentOS 7 and I think its a problem of requirements/dependencies, especially "curl".

[aaa@localhost build]$ cmake -DCMAKE_INSTALL_PREFIX=/home/aaa/frvt-master/11/floopcz ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
...
-- Build files have been written to: /home/aaa/tensorflow_cc/tensorflow_cc/build

[aaa@localhost build]$ make
Scanning dependencies of target tensorflow_base
[ 12%] Creating directories for 'tensorflow_base'
[ 25%] Performing download step (download, verify and extract) for 'tensorflow_base'
-- downloading...
       src='https://github.com/tensorflow/tensorflow/archive/v2.3.0.tar.gz'
       dst='/home/aaa/tensorflow_cc/tensorflow_cc/build/tensorflow/v2.3.0.tar.gz'
       timeout='none'
error: downloading 'https://github.com/tensorflow/tensorflow/archive/v2.3.0.tar.gz' failed
  status_code: 1
  status_string: "Unsupported protocol"
  log:
  --- LOG BEGIN ---
  Protocol "https" not supported or disabled in libcurl
Closing connection -1

  --- LOG END ---
-- Retrying...
-- downloading...
       src='https://github.com/tensorflow/tensorflow/archive/v2.3.0.tar.gz'
       dst='/home/aaa/tensorflow_cc/tensorflow_cc/build/tensorflow/v2.3.0.tar.gz'
       timeout='none'
error: downloading 'https://github.com/tensorflow/tensorflow/archive/v2.3.0.tar.gz' failed
  status_code: 1
  status_string: "Unsupported protocol"
  log:
  --- LOG BEGIN ---
  Protocol "https" not supported or disabled in libcurl
Closing connection -1

  --- LOG END ---
-- Retry after 5 seconds (attempt #2) ...
-- downloading...
       src='https://github.com/tensorflow/tensorflow/archive/v2.3.0.tar.gz'
       dst='/home/aaa/tensorflow_cc/tensorflow_cc/build/tensorflow/v2.3.0.tar.gz'
       timeout='none'
error: downloading 'https://github.com/tensorflow/tensorflow/archive/v2.3.0.tar.gz' failed
  status_code: 1
  status_string: "Unsupported protocol"
  log:
  --- LOG BEGIN ---
  Protocol "https" not supported or disabled in libcurl
Closing connection -1

**Comment by fisakhan** [comment]
Executing this command "curl https://github.com/tensorflow/tensorflow/archive/v2.3.0.tar.gz" generates the following output

<html><body>You are being <a href="https://codeload.github.com/tensorflow/tensorflow/tar.gz/v2.3.0">redirected</a>.</body></html>[20face@localhost build]$

However, I can successfully download the mentioned file using the following command.
wget https://github.com/tensorflow/tensorflow/archive/v2.3.0.tar.gz

**Comment by fisakhan** [comment]
Executing this command "curl https://github.com/tensorflow/tensorflow/archive/v2.3.0.tar.gz" generates the following output

<html><body>You are being <a href="https://codeload.github.com/tensorflow/tensorflow/tar.gz/v2.3.0">redirected</a>.</body></html>[aaa@localhost build]$

However, I can successfully download the mentioned file using the following command.
wget https://github.com/tensorflow/tensorflow/archive/v2.3.0.tar.gz

**Comment by fisakhan** [comment]
Information about curl and libcurl on my computer:

[aaa@localhost build]$ which curl
/usr/bin/curl
[aaa@localhost build]$ whereis curl
curl: /usr/bin/curl /usr/share/man/man1/curl.1.gz
[aaa@localhost build]$ curl --version
curl 7.72.0 (x86_64-redhat-linux-gnu) libcurl/7.72.0 NSS/3.44 zlib/1.2.7 libpsl/0.7.0 (+libicu/50.1.2) libssh2/1.9.0 nghttp2/1.33.0
Release-Date: 2020-08-19
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL UnixSockets
[aaa@localhost build]$ ldd /usr/bin/curl | grep libcurl
	libcurl.so.4 => /usr/lib64/libcurl.so.4 (0x00007f009921d000)

**Comment by fisakhan** [comment]
Solved.
Instead of " file(DOWNLOAD ...)" in /tensorflow_cc/tensorflow_cc/build/tensorflow-stamp/download-tensorflow_base.cmake, I manually downloaded tensorflow to "tensorflow_cc/tensorflow_cc/build/tensorflow/v2.3.0.tar.gz" and added "return()" after the statement "message(STATUS "File already exists but no hash specified (use URL_HASH): ... from URL.")"

**Comment by FloopCZ** [comment]
ok, strange though, since your `curl --version` lists https. Check that cmake is linked to the right libcurl version:
```
ldd /usr/bin/cmake | grep libcurl
```
