### ISSUE TITLE
Q: How to pass `--config=cuda` using CMake?

### ISSUE THREAD

**Issue by PharrellWANG** [FloopCZ/tensorflow_cc#24]
How to enable GPU support using CMake? 

I know that if Bazel is used, there is a flag can be passed: `--config=cuda`. But how to do it in CMake?

**Comment by FloopCZ** [comment]
So far, this is done automatically whenever `/opt/cuda` directory exists. See https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/build_tensorflow.sh#L22.

**Comment by PharrellWANG** [comment]
@FloopCZ 
The first time i use this project, i have not modified the path `/opt/cuda`, but i was able to install it.
Later, I looked back to this project after i have more understanding of CMake, I changed that to `/usr/local/cuda`, and compiled then installed again. But it seems does not work. 

According to your information "this is done automatically whenever `/opt/cuda` directory exists", I am thinking that maybe even i installed twice, but only the installation is still the one being used.

I would like to do it again. But here comes the question: how to uninstall all the stuffs which were installed by this project?

**Comment by FloopCZ** [comment]
You can remove it all by doing something like:
```
sudo rm -rv /usr/local/include/tensorflow_cc /usr/local/lib/tensorflow_cc /usr/local/lib/cmake/TensorflowCC
```

And you can also remove the whole build directory by something like
```
rm -r tensorflow_cc/build ~/.cache
```

**Comment by PharrellWANG** [comment]
@FloopCZ 
Ok, thank you for the helpful information. This project is really nice.
