### ISSUE TITLE
Support TF2.3.0

### ISSUE THREAD

**Issue by Aurelius84** [FloopCZ/tensorflow_cc#240]
I'm training model with tensorflow==2.3.0. 

I would appreciate it very much if  you plan to support version 2.3.0

**Comment by fisakhan** [comment]
Its already supporting 2.3.0. After clonning/downloading the repository

Replace version number to 3.1.0 in /tensorflow_cc/Dockerfiles/BAZEL_VERSION
Replace version number to 2.3.0 in /tensorflow_cc/tensorflow_cc/PROJECT_VERSION
Follow the rest of the steps.

Done.
