### ISSUE TITLE
Can't support some tensorflow function

### ISSUE THREAD

**Issue by fisakhan** [FloopCZ/tensorflow_cc#241]
Some important tensorflow functions like SavedModelBundle generate errors. In my following simple code everything runs fine except the line "tensorflow::SavedModelBundle bundle;". If I uncomment this statement, then it generates the given error.
```
#include <fstream>
#include <utility>
#include <vector>
#include"google/protobuf/message.h"
#include "tensorflow/cc/ops/const_op.h"
#include "tensorflow/cc/ops/image_ops.h"
#include "tensorflow/cc/ops/standard_ops.h"
#include "tensorflow/cc/saved_model/loader.h"//savedmodelbundle
#include "tensorflow/cc/saved_model/constants.h"
#include "tensorflow/cc/saved_model/signature_constants.h"
#include "tensorflow/cc/saved_model/tag_constants.h"// kSavedModelTagServe
#include "tensorflow/core/framework/graph.pb.h"
#include "tensorflow/core/framework/tensor.h"
#include "tensorflow/core/graph/default_device.h"
#include "tensorflow/core/graph/graph_def_builder.h"
#include "tensorflow/core/lib/core/errors.h"
#include "tensorflow/core/lib/core/stringpiece.h"
#include "tensorflow/core/lib/core/threadpool.h"
#include "tensorflow/core/lib/io/path.h"
#include "tensorflow/core/lib/strings/str_util.h"
#include "tensorflow/core/lib/strings/stringprintf.h"
#include "tensorflow/core/platform/env.h"
#include "tensorflow/core/platform/init_main.h"
#include "tensorflow/core/platform/logging.h"
#include "tensorflow/core/platform/types.h"
#include "tensorflow/core/public/session.h"
#include "tensorflow/core/util/command_line_flags.h"

using tensorflow::Flag;
using tensorflow::int32;
using tensorflow::Status;
using tensorflow::string;
using tensorflow::Tensor;
using tensorflow::tstring;
using namespace tensorflow;

int main(int argc, char* argv[]) {

  tensorflow::SavedModelBundle bundle;

  tensorflow::SessionOptions session_options;
  tensorflow::RunOptions run_options;
  tensorflow::Status status;

  return 0;
}
```

CMakeFiles/example.dir/exam.cpp.o: In function `google::protobuf::internal::MapField<tensorflow::ConfigProto_DeviceCountEntry_DoNotUse, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, (google::protobuf::internal::WireFormatLite::FieldType)9, (google::protobuf::internal::WireFormatLite::FieldType)5, 0>::MutableMap()':
exam.cpp:(.text._ZN6google8protobuf8internal8MapFieldIN10tensorflow37ConfigProto_DeviceCountEntry_DoNotUseENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiLNS1_14WireFormatLite9FieldTypeE9ELSC_5ELi0EE10MutableMapEv[_ZN6google8protobuf8internal8MapFieldIN10tensorflow37ConfigProto_DeviceCountEntry_DoNotUseENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiLNS1_14WireFormatLite9FieldTypeE9ELSC_5ELi0EE10MutableMapEv]+0x14): undefined reference to `google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField() const'
exam.cpp:(.text._ZN6google8protobuf8internal8MapFieldIN10tensorflow37ConfigProto_DeviceCountEntry_DoNotUseENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiLNS1_14WireFormatLite9FieldTypeE9ELSC_5ELi0EE10MutableMapEv[_ZN6google8protobuf8internal8MapFieldIN10tensorflow37ConfigProto_DeviceCountEntry_DoNotUseENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiLNS1_14WireFormatLite9FieldTypeE9ELSC_5ELi0EE10MutableMapEv]+0x34): undefined reference to `google::protobuf::internal::MapFieldBase::SetMapDirty()'
collect2: error: ld returned 1 exit status
CMakeFiles/example.dir/build.make:95: recipe for target 'example' failed
make[2]: *** [example] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/example.dir/all' failed
make[1]: *** [CMakeFiles/example.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by FloopCZ** [comment]
It appears as if the library did not contain the necessary protobuf symbols. What works for me is linking the protobuf from your OS:
```
find_package(Protobuf)
target_link_libraries(example ${Protobuf_LIBRARIES})
```
It is a bit unfortunate though.

**Comment by elfprince13** [comment]
> It appears as if the library did not contain the necessary protobuf symbols. What works for me is linking the protobuf from your OS:
> 
> ```
> find_package(Protobuf)
> target_link_libraries(example ${Protobuf_LIBRARIES})
> ```
> 
> It is a bit unfortunate though.

The snippet I used which is a bit cleaner is:
```cmake
find_package(TensorflowCC)
if(TARGET TensorflowCC::TensorflowCC)
	target_link_libraries(TensorflowCC::TensorflowCC INTERFACE protobuf::libprotobuf)
endif()
```

I noticed other people with similar problems turned up on Google suggested using `SavedModelBundleLite`, but in my case that just gave a different linking error (still with protobuf, just different symbols).
