### ISSUE TITLE
Change in source code of TensorFlow

### ISSUE THREAD

**Issue by fisakhan** [FloopCZ/tensorflow_cc#242]
How can I change/modify/add the source code of TensorFlow? 

For example, while running the following statement I want tensorflow to display a message "Hello World".
Status status = NewSession(SessionOptions(), &session);

I think, I should change the source code after cmake .. and before make. But there are no cpp or cc files at this stage that I can modify.

**Comment by jappoz** [comment]
As far as I know tensorflow repo is downloaded while doing make and it is stored in the build directory.
I guess you should launch make, wait for the download to complete, stop the compilation, locate the files you may want to modify and relaunch make command.

**Comment by FloopCZ** [comment]
Thank you @jappoz, it is as you say. The second option is to create your own fork of TensorFlow and point the URL to this fork:
https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/TensorflowBase.cmake
