### ISSUE TITLE
Unable to build shared library

### ISSUE THREAD

**Issue by AdamHeavens** [FloopCZ/tensorflow_cc#25]
Hi,

When trying to build the shared library I get the following error

You have bazel 0.7.0 installed.
Configuration finished
WARNING: The lower priority option '-c opt' does not override the previous value '-c opt'
ERROR: /home/adamheavens/.cache/bazel/_bazel_adamheavens/87be3c52a121629cbd86bb264477a61d/external/io_bazel_rules_closure/closure/private/defs.bzl:27:16: The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false
ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors
ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors
INFO: Elapsed time: 0.977s
FAILED: Build did NOT complete successfully (0 packages loaded)
CMakeFiles/tensorflow_shared.dir/build.make:106: recipe for target 'tensorflow-stamp/tensorflow_shared-configure' failed
make[2]: *** [tensorflow-stamp/tensorflow_shared-configure] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/tensorflow_shared.dir/all' failed
make[1]: *** [CMakeFiles/tensorflow_shared.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Any ideas?

Thanks

Adam

**Comment by FloopCZ** [comment]
Hi, it seems that your bazel is out-of-date. Can you please update your system, remove `tensorflow_cc/build`, checkout `tensorflow_cc` branch `tf-1.4.0` and try over?

**Comment by FloopCZ** [comment]
Also in the `tf-1.4.0` branch, the `Requirements` section slightly changed, since now, `g++-6` is used instead of `g++-5`. Please see https://github.com/FloopCZ/tensorflow_cc/tree/tf-1.4.0.

**Comment by akucia** [comment]
Rebuilding from the `tf-1.4.0` branch solved the problem for me. Thanks!

**Comment by FloopCZ** [comment]
Glad to hear that. The branch will hopefully soon be merged to `master`.
