### ISSUE TITLE
Cudnn conflicts 

### ISSUE THREAD

**Issue by NicolayP** [FloopCZ/tensorflow_cc#250]
Hi, I'm trying to compile and install tensorflow 2.1 with cuda toolkit 10.1 and cudnn 7.6.5. But I have matlab installed which comes shipped with cudnn7.5. Thus the  line 
```
 export TF_CUDNN_VERSION="$(find /opt /usr -name 'libcudnn.so.*' | tail -n1 | sed -r 's/^.*\.so\.//')"
```
Returns the value 7.5 and not the value 7.6 expected. 

```
find /opt /usr -name 'libcudnn.so.*' 
```

returns :

/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/MATLAB/R2019b/bin/glnxa64/libcudnn.so.7
/usr/local/MATLAB/R2019b/bin/glnxa64/libcudnn.so.7.5.0

my quick fix is to limit the search to: 

```
/usr/local/{CUDAVERSION}/
```

As, if my memory is correct, is where nvidia installation guides suggests to put the cudnn header an lib. 

Same for NCCL

Btw, it could be nice to add support for the number of jobs 
```
make -j 4
```

calls bazel with all available threads, and make my laptop crash

**Comment by FloopCZ** [comment]
Hi,

1) regarding the cudnn path - unfortunately, cuda is not installed to `/usr/local/{CUDAVERSION}` in all cases (e.g., on Arch, not sure about Ubuntu). But I could change the `find` to also require `cuda` in path, e.g.,
    ```
    find /opt /usr -name 'libcudnn.so.*' -path '*/cuda*'
    ```
Would that work for you?

2) In this case, `make -j4` does not affect the number of jobs for `bazel`. Extra parameters for bazel can be passed [here](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/build_tensorflow.sh.in#L100). But if your system is sensitive to the number of threads, you may want to edit your `.bazelrc` adding something like:
    ```
    build --jobs 2 --ram_utilization_factor 50
    ```

**Comment by NicolayP** [comment]
Hi,

The fix should work or at least it rejects Matlab paths! I'm not aware of any software other than Matlab that will have its own version of cudnn. Thanks for the help!

Closing the issue
