### ISSUE TITLE
Can I compute gradient of the model output w.r.t input? 

### ISSUE THREAD

**Issue by junhyeokahn** [FloopCZ/tensorflow_cc#252]
Hello,
First of all, I appreciate your effort to maintain this nice repo.
I am wondering if I can get a gradient of the network model output w.r.t input similar to [this function](https://www.tensorflow.org/api_docs/python/tf/GradientTape?hl=zh-cn) in ```tensorflow```.

**Comment by FloopCZ** [comment]
As far as I know, the gradient support is rather poor in the C++ API. See
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/cc/gradients
and https://github.com/tensorflow/tensorflow/issues/6268
