### ISSUE TITLE
fatal error: tensorflow/compiler/xla/pjrt/cpu_device.h: No such file or directory

### ISSUE THREAD

**Issue by Maxstu-zz** [FloopCZ/tensorflow_cc#254]
Hello,

I successfully installed and builded TensorflowCC (tensorflow 2.4) on Ubuntu 18.04 and tried to run the example with some additional header files.

But everytime I try to include any from the xla/pjrt folder or the xla/tools, I get the error that there is no such file or directory:

```
fatal error: tensorflow/compiler/xla/pjrt/cpu_device.h: No such file or directory
 #include <tensorflow/compiler/xla/pjrt/cpu_device.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/example.dir/build.make:62: recipe for target 'CMakeFiles/example.dir/example.cpp.o' failed
make[2]: *** [CMakeFiles/example.dir/example.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/example.dir/all' failed
make[1]: *** [CMakeFiles/example.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
I am used to work with bazel and tensorflow, so I am quite new to cmake. Is there something I am missing? Do I need to specify them directly in the CMakeList.txt?

Thank you for your help!

**Comment by FloopCZ** [comment]
Hi, the installed header files are taken from the official `install_headers` target:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/BUILD#L1067
So if it is missing something you need, and you know how to work with Bazel, the best way would be to create a PR to the official tensorflow repo.
