### ISSUE TITLE
x86_64-linux-gnu-gcc-9: fatal error: Killed signal terminated program cc1plus compilation terminated

### ISSUE THREAD

**Issue by mugeshk97** [FloopCZ/tensorflow_cc#255]
![image](https://user-images.githubusercontent.com/58897850/109259636-9e994c80-7822-11eb-9a17-732213b63f94.png)

**Comment by FloopCZ** [comment]
Is it possible that you ran out of RAM memory?

**Comment by mugeshk97** [comment]
My system ram is 8GB do I need more to compile

**Comment by FloopCZ** [comment]
Depends on which version you build, but yes, you may need more. Or you can try #256.

**Comment by FloopCZ** [comment]
You should fit in 8GB using `cmake -DLOCAL_RAM_RESOURCES=2048 -DLOCAL_CPU_RESOURCES=4 ..`
