### ISSUE TITLE
Using the library from C++17 after building libraries in C++11 mode (Arch)

### ISSUE THREAD

**Issue by mooskagh** [FloopCZ/tensorflow_cc#266]
The discussion started in Arch bug tracker at https://bugs.archlinux.org/task/65953 and I'd like to ask for opinion of fixing the issue here.

In Arch pre-built tensorflow_cc binaries are built with C++11, and that causes problems when using them from C++17.

Tensorflow_cc library uses own copy of Absl, and uses `absl::string_view` in function signatures.
`absl::string_view` is mapped to `std::string_view` if C++17 is detected, and to own implementation if C++17 is not.
That leads to linker errors like this when using Arch tensorflow_cc library from C++17 code:
```
test.cc:(.text+0x2b6): undefined reference to `tensorflow::ops::Conv2D::Conv2D(tensorflow::Scope const&, tensorflow::Input, tensorflow::Input, absl::Span<int const> const&, std::basic_string_view<char, std::char_traits<char> >)'
```

One workaround is to comment out this line in /usr/include/tensorflow/absl/base/config.h:
```
#define ABSL_HAVE_STD_STRING_VIEW 1
```

This will make the library look for the custom absl::string_view implementation even if tensorflow is called from C++17.

It doesn't look nice, so I wonder if you have any other suggestion?

**Comment by FloopCZ** [comment]
I would not be opposed to supporting `CMAKE_CXX_STANDARD` parameter and setting C++14 or C++17 as default. TF will eventually get there anyway and this library is experimental enough so that those who need a specific version can rebuild it to suit their needs. See #269 if that is something that helps.
