### ISSUE TITLE
nvcc tries to use gcc-6

### ISSUE THREAD

**Issue by sjdrc** [FloopCZ/tensorflow_cc#27]
Hi there, thanks very much for the repo. I am on Ubuntu 16.04 with CUDA 8.0 and CUDNN 6.0.

I've been trying to compile the shared library but it seems that nvcc is trying to use gcc-6 which it is not compatible with. I've created the following symlinks but this did not fix the issue:

```
/opt/cuda -> /usr/local/cuda
/usr/bin/gcc-5 -> /usr/local/cuda/bin/gcc
/usr/bin/gcc-5 -> /usr/local/cuda/bin/g++
```

The plain gcc binary is 5.4:

```
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

After removing gcc-6 and g++-6 from my system, the bazel configure step prompts me:

```
Invalid gcc path. /usr/bin/gcc-6 cannot be found
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc-5]: 
```

Can we force bazel to always ask which version of gcc to use for host compiler?

**Comment by sjdrc** [comment]
```
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

the gcc binary is definitely the right version too

**Comment by sjdrc** [comment]
After removing gcc-6 and g++-6 from my system, the bazel configure step prompts me:

```
Invalid gcc path. /usr/bin/gcc-6 cannot be found
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc-5]: 
```

**Comment by sjdrc** [comment]
I changed ```gcc-6``` to ```gcc-5``` in ```tensorflow_cc/cmake/build_tensorflow.sh``` to fix this issue. I actually needed to also make a change to the tensorflow source code in ```cuda/cuda_dnn.cc``` to remove a _v6 function to a different block in order to get the code to compile. However, I am now running into the same error as https://github.com/FloopCZ/tensorflow_cc/issues/23.

**Comment by FloopCZ** [comment]
Thank you for the info, changing build files is also an option. Other option should be a fresh CUDA driver from Nvidia website, which (I believe) supports `g++-6` out of the box.
