### ISSUE TITLE
what is the Tensorflow version that i can compile with bazel 3.7.1?

### ISSUE THREAD

**Issue by yaira24** [FloopCZ/tensorflow_cc#273]
I try to compile the project on CentOS 8.2
the last version of Bazel on centos is 3.7.1. 
when I compile the last version I get an error that the installation required 3.7.2.
what version of TensorFlow will be compiled with Bazel 3.7.1 
and how to change the TensorFlow version to make it work. 
thanks

**Comment by FloopCZ** [comment]
Hi, you can either install [Bazel 3.7.2](https://github.com/bazelbuild/bazel/releases/tag/3.7.2) manually or try to set [`TENSORFLOW_TAG`](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/CMakeLists.txt#L13) CMake parameter (e.g., `cmake -DTENSORFLOW_TAG=v2.4.0` ..)
