### ISSUE TITLE
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Michahial** [FloopCZ/tensorflow_cc#276]
I am trying out the Windows editor for unity

OS: Windows
Python : 3.9
Bazel : 4.0.1

PS C:\Users\holos\Downloads\MediaPipeUnityPlugin> python build.py build --desktop cpu --include_opencv_libs -v
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_proto_srcs`
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
ERROR: Skipping '/mediapipe_api:mediapipe_proto_srcs': not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/mediapipe_api:mediapipe_proto_srcs'
WARNING: Target pattern parsing failed.
ERROR: not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/mediapipe_api:mediapipe_proto_srcs'
INFO: Elapsed time: 0.148s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "/c/Users/holos/Downloads/MediaPipeUnityPlugin/build.py", line 392, in <module>
    Argument().command().run()
  File "/c/Users/holos/Downloads/MediaPipeUnityPlugin/build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "/c/Users/holos/Downloads/MediaPipeUnityPlugin/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

**Comment by FloopCZ** [comment]
Hi, you have probably created this issue in a wrong project. Maybe you meant https://github.com/homuler/MediaPipeUnityPlugin
