### ISSUE TITLE
Bazel build fails on both macOS and Ubuntu

### ISSUE THREAD

**Issue by raash1d** [FloopCZ/tensorflow_cc#280]
I followed the build instructions but when I `make` the build fails with a bunch of invalid certificate warnings. But the main error is when bazel is fetching the "icu" repo.

**Comment by FloopCZ** [comment]
Hi, can you send the error itself? I have not encountered it and it has not happened on September 15 in the regular [CI run](http://oak.floop.cz:8080/job/tensorflow_cc/468/console).

**Comment by raash1d** [comment]
Hi,

I think you can close this since it is a tensorflow related issue.

The build fails when it tries to download certain compressed dependencies and validates it's sha256, e.g. the python license file. The bazel build files sometimes have 2 links to download the same file, for redundancy. But links have the same exact file but their sha256 hash values are different. Bazel allows only one value to be put in i believe. Hence, if luckily you end up downloading from the link that matches the expected hash value, you're gold. But if the build cannot reach that first link, it tries the second one, gets the file and sees it's hash value is different and fails.

I understand it's a security measure but bazel really disappointed me here.

Anyways, this is nothing to do with tensorflow_cc.

**Comment by FloopCZ** [comment]
Huh, thanks for the info.
