### ISSUE TITLE
error while built

### ISSUE THREAD

**Issue by nqthai309** [FloopCZ/tensorflow_cc#285]
I get this error when doing build, can someone help me!

![image](https://user-images.githubusercontent.com/61822545/147413022-bfaf89a2-2eea-4f76-ba86-d0c46cef4910.png)

[ 12%] Performing build step for 'tensorflow_base'
CUDA support enabled
find: ‘/opt/containerd’: Permission denied
find: ‘/opt/containerd’: Permission denied
You have bazel 3.7.2 installed.
Found CUDA 11.2 in:
    /usr/local/cuda-11.2/targets/x86_64-linux/lib
    /usr/local/cuda-11.2/targets/x86_64-linux/include
Found cuDNN 8 in:
    /usr/local/cuda-11.2/targets/x86_64-linux/lib
    /usr/local/cuda-11.2/targets/x86_64-linux/include

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=mkl_aarch64 	# Build with oneDNN and Compute Library for the Arm Architecture (ACL).
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v1          	# Build with TensorFlow 1 API instead of TF 2 API.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=nogcp       	# Disable GCP support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=106
INFO: Reading rc options for 'build' from /media/thai/A0B6A6B3B6A688FC/code/PROJECT_BI/DEPLOYMENT/tensorflow_cc/tensorflow_cc/build/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /media/thai/A0B6A6B3B6A688FC/code/PROJECT_BI/DEPLOYMENT/tensorflow_cc/tensorflow_cc/build/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from /media/thai/A0B6A6B3B6A688FC/code/PROJECT_BI/DEPLOYMENT/tensorflow_cc/tensorflow_cc/build/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/local/lib/python3.8/dist-packages --python_path=/usr/bin/python3 --action_env TF_CUDA_VERSION=11.2 --action_env TF_CUDNN_VERSION=8 --action_env TF_NCCL_VERSION= --action_env TF_CUDA_PATHS=/opt/cuda,/usr/local/cuda,/usr/local,/usr/cuda,/usr --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda-11.2 --action_env NCCL_INSTALL_PATH=/usr --action_env TF_CUDA_COMPUTE_CAPABILITIES=sm_52,sm_53,sm_60,sm_61,sm_62,sm_70,sm_72,sm_75,sm_80,sm_86,compute_86 --action_env LD_LIBRARY_PATH=/usr/local/cuda-11.2/lib64::/home/thai/opencv_build/opencv/build/lib --action_env GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-9 --config=cuda
INFO: Found applicable config definition build:short_logs in file /media/thai/A0B6A6B3B6A688FC/code/PROJECT_BI/DEPLOYMENT/tensorflow_cc/tensorflow_cc/build/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /media/thai/A0B6A6B3B6A688FC/code/PROJECT_BI/DEPLOYMENT/tensorflow_cc/tensorflow_cc/build/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:cuda in file /media/thai/A0B6A6B3B6A688FC/code/PROJECT_BI/DEPLOYMENT/tensorflow_cc/tensorflow_cc/build/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:opt in file /media/thai/A0B6A6B3B6A688FC/code/PROJECT_BI/DEPLOYMENT/tensorflow_cc/tensorflow_cc/build/tensorflow/.tf_configure.bazelrc: --copt=-march=native --host_copt=-march=native
INFO: Found applicable config definition build:monolithic in file /media/thai/A0B6A6B3B6A688FC/code/PROJECT_BI/DEPLOYMENT/tensorflow_cc/tensorflow_cc/build/tensorflow/.bazelrc: --define framework_shared_object=false
INFO: Found applicable config definition build:cuda in file /media/thai/A0B6A6B3B6A688FC/code/PROJECT_BI/DEPLOYMENT/tensorflow_cc/tensorflow_cc/build/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:linux in file /media/thai/A0B6A6B3B6A688FC/code/PROJECT_BI/DEPLOYMENT/tensorflow_cc/tensorflow_cc/build/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false
INFO: Found applicable config definition build:dynamic_kernels in file /media/thai/A0B6A6B3B6A688FC/code/PROJECT_BI/DEPLOYMENT/tensorflow_cc/tensorflow_cc/build/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: /home/thai/.cache/bazel/_bazel_thai/9a2201ed861555a8179fff47153819a5/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: --discard_analysis_cache was used in the previous build, discarding analysis cache.
INFO: Analyzed 2 targets (0 packages loaded, 22682 targets configured).
INFO: Found 2 targets...
ERROR: /media/thai/A0B6A6B3B6A688FC/code/PROJECT_BI/DEPLOYMENT/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/core/kernels/BUILD:5344:18: C++ compilation of rule '//tensorflow/core/kernels:training_ops' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/tensorflow/core/kernels/_objs/training_ops/training_ops.pic.d ... (remaining 194 argument(s) skipped)
x86_64-linux-gnu-gcc-9: fatal error: Killed signal terminated program cc1plus
compilation terminated.
INFO: Elapsed time: 5667.512s, Critical Path: 2345.97s
INFO: 7546 processes: 49 internal, 7497 local.
FAILED: Build did NOT complete successfully
make[2]: *** [CMakeFiles/tensorflow_base.dir/build.make:119: tensorflow-stamp/tensorflow_base-build] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/tensorflow_base.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by FloopCZ** [comment]
This looks like you run out of memory. What are your specs? You may want to use the docker image where the library is already built for you.
