### ISSUE TITLE
It seems that Tensorflow_cc does not use the GPU on my installation

### ISSUE THREAD

**Issue by ShmulikHass** [FloopCZ/tensorflow_cc#288]
I am using a new and clean installation and build of Tensorflow_cc version 2.7 from sources on Ubuntu 20.04 with CUDA 11.6 ( with Nvidia drivers 510, CUDNN 8.3.3.40, etc ). 
All works "fine", including the example provided.
But when running  our application that uses TF , it seems that it does not use the GPU but the CPU. ( according to performance )
My computer has GPU -  NVIDIA GeForce GTX 1650 Ti
We suspect some dependency with CUDA version, or the fact we use previously TF1 graph (but it works ok on other TF2 environment) or something wrong in configurations during build or run.

Can you suggest what can be the reason for this ?
How we can control/monitor if TF uses GPU or CPU on run time ?

Thanks

**Comment by ShmulikHass** [comment]
During the build I see the message:
CUDA Support Disabled.

Maybe it is related to the problem. CUDA is installed and works ok.

**Comment by ShmulikHass** [comment]
Update: I found that NVCC is not in the path and the script decide that CUDA is not installed.
so I added the path and now get the error

ERROR: /home/shmulik/.cache/bazel/_bazel_shmulik/4ba6fc284e9b23cd0a456fff9970072d/external/com_google_protobuf/BUILD:110:11: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/external/com_google_protobuf/_objs/protobuf_lite/structurally_valid.d ... (remaining 40 argument(s) skipped)
x86_64-linux-gnu-gcc-11: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
compilation terminated.

**Comment by FloopCZ** [comment]
Hi, are you sure you have installed all the dependencies and the PATH variable is not broken? This looks like a `g++` problem, is the command available after changing the PATH and what does `which g++` say?

**Comment by ShmulikHass** [comment]
Hi,
I am using "clean" Ubuntu 20.04 installation and I tried to follow all the instructions. 
I was able to build and run  the tensorflow_cc, but found out that CUDA was disabled, since the script is checking NVCC which was not in the path. ( This was not required anywhere). When I added the path to NVCC, the build was changed and then failed as above.
This is the G++ version I have :  g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
This is the printenv below. Do you see anything missing ?
by the way, the error says cc1plus  is missing.
I can found it in several folders: /usr/lib/gcc/x86_64-linux-gnu/9  and /7.
I can add path to that location, but I'm not sure this is the real root cause here.
Btw, I'm using CUDA 11.6.  do you think any relation to that ?

----------------------------------------------printenv-----------------------
SHELL=/bin/bash
ROS_VERSION=1
SESSION_MANAGER=local/shmulik-LT:@/tmp/.ICE-unix/2558,unix/shmulik-LT:/tmp/.ICE-unix/2558
QT_ACCESSIBILITY=1
COLORTERM=truecolor
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
XDG_MENU_PREFIX=gnome-
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
GTK_IM_MODULE=ibus
PKG_CONFIG_PATH=/opt/ros/noetic/lib/pkgconfig
ROS_PYTHON_VERSION=3
LANGUAGE=en_IL:en
QT4_IM_MODULE=ibus
GNOME_SHELL_SESSION_MODE=ubuntu
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
XMODIFIERS=@im=ibus
CAMERA_SUITE_INCLUDE_PATH=/usr/include/framos/camerasuite
DESKTOP_SESSION=ubuntu
SSH_AGENT_PID=2456
ROS_PACKAGE_PATH=/opt/ros/noetic/share
GTK_MODULES=gail:atk-bridge
ROSLISP_PACKAGE_DIRECTORIES=
PWD=/home/shmulik
CAMERA_SUITE_DOC_PATH=/usr/doc/framos/camerasuite
XDG_SESSION_DESKTOP=ubuntu
LOGNAME=shmulik
XDG_SESSION_TYPE=x11
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
XAUTHORITY=/run/user/1000/gdm/Xauthority
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
WINDOWPATH=2
GTE4_PATH=/home/shmulik/FFR/GTE
CAMERA_SUITE_PACKAGE=/usr/src/framos/camerasuite/CMakePackages
HOME=/home/shmulik
USERNAME=shmulik
IM_CONFIG_PHASE=1
LANG=en_IL
ROS_ETC_DIR=/opt/ros/noetic/etc/ros
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
XDG_CURRENT_DESKTOP=ubuntu:GNOME
VTE_VERSION=6003
CAMERA_SUITE_SRC_PATH=/usr/src/framos/camerasuite
CMAKE_PREFIX_PATH=/opt/ros/noetic
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/ef1c644b_7635_4bdb_a501_53e460841fd0
CAMERA_SUITE_GENICAM_ROOT_V3_0=/usr/src/framos/camerasuite/GenICam
INVOCATION_ID=b93fbbb9b62d42bca1396bce7babf9ac
MANAGERPID=2228
CAMERA_SUITE_PATH=/usr/src/framos/camerasuite
CAMERA_SUITE_TOOLCHAIN_PATH=/usr/src/framos/camerasuite/Toolchain
CLUTTER_IM_MODULE=ibus
GJS_DEBUG_OUTPUT=stderr
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_SESSION_CLASS=user
GENICAM_LOG_CONFIG_V3_0=/usr/src/framos/camerasuite/GenICam/log/config-unix/DefaultLogging.properties
PYTHONPATH=/opt/ros/noetic/lib/python3/dist-packages
TERM=xterm-256color
LESSOPEN=| /usr/bin/lesspipe %s
USER=shmulik
GNOME_TERMINAL_SERVICE=:1.98
FFRPATH=/home/shmulik/FFR
DISPLAY=:1
SHLVL=1
ROS_MASTER_URI=http://localhost:11311
QT_IM_MODULE=ibus
CAMERA_SUITE_CUSTOM_PATH=/home/shmulik/.local/custom
LD_LIBRARY_PATH=/opt/ros/noetic/lib
XDG_RUNTIME_DIR=/run/user/1000
CAMERA_SUITE_LIB_PATH=/usr/lib/framos/camerasuite
JOURNAL_STREAM=8:54031
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
CAMERA_SUITE_GENICAM_CACHE_V3_0=/home/shmulik/.cache/genicam
PATH=/opt/ros/noetic/bin:/home/shmulik/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda-11.6/bin:/snap/bin
GDMSESSION=ubuntu
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
ROS_ROOT=/opt/ros/noetic/share/ros
ROS_DISTRO=noetic
OLDPWD=/home/shmulik/Desktop
_=/usr/bin/printenv

**Comment by ShmulikHass** [comment]
update: I tried to add path to /usr/lib/gcc/x86_64-linux-gnu/9/cc1plus
before that, I have used a PATH without NVCC so CUDA was disabled and everything was compiled and build ok, including example.cpp which runs without GPU.
Now, using path that includes both NVCC and cc1plus, I got the following error, during build - 
Looks as comptability issue with gcc and cc1plus ?

ERROR: /home/shmulik/.cache/bazel/_bazel_shmulik/4ba6fc284e9b23cd0a456fff9970072d/external/com_google_protobuf/BUILD:301:11: C++ compilation of rule '@com_google_protobuf//:protoc_lib' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/external/com_google_protobuf/_objs/protoc_lib/csharp_repeated_primitive_field.d ... (remaining 48 argument(s) skipped)
cc1plus: warning: unrecognized gcc debugging option: u
cc1plus: warning: unrecognized gcc debugging option: m
cc1plus: warning: unrecognized gcc debugging option: b
cc1plus: warning: unrecognized gcc debugging option: s
cc1plus: warning: unrecognized gcc debugging option: e
cc1plus: warning: unrecognized gcc debugging option: -
cc1plus: warning: unrecognized gcc debugging option: e
cc1plus: warning: unrecognized gcc debugging option: t
cc1plus: error: too many filenames given.  Type cc1plus --help for usage
INFO: Elapsed time: 22.449s, Critical Path: 0.97s
INFO: 112 processes: 96 internal, 16 local.
FAILED: Build did NOT complete successfully
make[2]: *** [CMakeFiles/tensorflow_base.dir/build.make:119: tensorflow-stamp/tensorflow_base-build] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/tensorflow_base.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by FloopCZ** [comment]
What does `which g++` say?

**Comment by ShmulikHass** [comment]
g++ gives the following version information:   9.4.0  ( Ubuntu 9.4.0-1ubuntu1~20.04.1)

**Comment by FloopCZ** [comment]
I mean literally the output of the following commands:
```
which g++
which nvcc
```
right before you try run `make`.

**Comment by FloopCZ** [comment]
Also, you can try the latest master, there have been a few fixes. Does the Docker image work for you?

**Comment by ShmulikHass** [comment]
> I mean literally the output of the following commands:
> 
> ```
> which g++
> which nvcc
> ```
> 
> right before you try run `make`.




shmulik@shmulik-LT:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Thu_Feb_10_18:23:41_PST_2022
Cuda compilation tools, release 11.6, V11.6.112
Build cuda_11.6.r11.6/compiler.30978841_0
shmulik@shmulik-LT:~$ g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by FloopCZ** [comment]
Can you run the command literally, please, including twe `which` directive?

**Comment by ShmulikHass** [comment]
> Also, you can try the latest master, there have been a few fixes. Does the Docker image work for you?

latest master is 2.9....Which

**Comment by ShmulikHass** [comment]
closed by mistake....

**Comment by ShmulikHass** [comment]
how can I change it to be open back ?

**Comment by ShmulikHass** [comment]
> Can you run the command literally, please, including the `which` directive?

shmulik@shmulik-LT:~$ which nvcc
/usr/local/cuda-11.6/bin/nvcc

**Comment by FloopCZ** [comment]
And the gcc ?

**Comment by ShmulikHass** [comment]
shmulik@shmulik-LT:~$ which g++
/usr/bin/g++
shmulik@shmulik-LT:~$ which gcc
/usr/bin/gcc

**Comment by FloopCZ** [comment]
Thank you, please remove you `build` folder, checkout #292 and try to rebuild.

**Comment by yaira24** [comment]
@ShmulikHass I have the same issue what fixes need to solve this issue?

**Comment by FloopCZ** [comment]
@yaira24 Please also try to remove the whole `build` folder, pull the latest master and try again.
