### ISSUE TITLE
Tag/release 2.6/2.7/2.8

### ISSUE THREAD

**Issue by Youw** [FloopCZ/tensorflow_cc#289]
Any (particular) plans to make a release? Or at least a tag?

I'm using the repository in my scripts, and recently started using TF 2.6.
Naturally I can no longer checkout as `-b v2.6.0`.

Would you be be willing to tag/name those commits even if not ready for a propper release?

**Comment by mchugai** [comment]
Hello @FloopCZ 
It will be great to have tag or release this versions

**Comment by FloopCZ** [comment]
Hi, I have skipped a few versions and it is difficult to find which commits with which patches would work with the current Ubuntu and Arch, so the latest release v2.8.0.

**Comment by Youw** [comment]
This is very nice anyway, thanks!

**Comment by mchugai** [comment]
Thanks!
