### ISSUE TITLE
is there a way to do this in windows

### ISSUE THREAD

**Issue by mouad-boumediene** [FloopCZ/tensorflow_cc#290]
i found out that windows doesn't support nvidia-docker which means i can't install the tensorflow-gpu in windows , is there a workaround ?

**Comment by FloopCZ** [comment]
Hi, sorry, I am not a Windows user and as such, it would be hard to maintain a Windows support. As far as I am aware, NVIDIA Docker does not support Windows either: https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#is-microsoft-windows-supported

**Comment by mouad-boumediene** [comment]
thanks, i installed linux for this purpose the image works great , thanks again.
    Le samedi 21 mai 2022, 16:44:15 UTC+2, Filip Matzner ***@***.***> a écrit :  
 
 


Hi, sorry, I am not a Windows user and as such, it would be hard to maintain a Windows support. As far as I am aware, NVIDIA Docker does not support Windows either: https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#is-microsoft-windows-supported
