### ISSUE TITLE
not all ops have been compiled

### ISSUE THREAD

**Issue by zakizhou** [FloopCZ/tensorflow_cc#3]
follow you instruction, I compiled tensorflow c++ library, its ok for small example like creating a session, but important math ops are missing like `tensorflow::ops::MatMul`, can you check this? Thank you very much!

**Comment by FloopCZ** [comment]
Hi, thank you for testing out tensorflow_cc. I have just successfully compiled the official example from [Tensorflow C++ API guide](https://www.tensorflow.org/api_guides/cc/guide) by linking against the TensorflowCC::Shared target.

```c++
#include <tensorflow/cc/client/client_session.h>
#include <tensorflow/cc/ops/standard_ops.h>
#include <tensorflow/core/framework/tensor.h>

int main() {
  using namespace tensorflow;
  using namespace tensorflow::ops;
  Scope root = Scope::NewRootScope();
  // Matrix A = [3 2; -1 0]
  auto A = Const(root, { {3.f, 2.f}, {-1.f, 0.f}});
  // Vector b = [3 5]
  auto b = Const(root, { {3.f, 5.f}});
  // v = Ab^T
  auto v = MatMul(root.WithOpName("v"), A, b, MatMul::TransposeB(true));
  std::vector<Tensor> outputs;
  ClientSession session(root);
  // Run and fetch v
  TF_CHECK_OK(session.Run({v}, &outputs));
  // Expect outputs[0] == [19; -3]
  LOG(INFO) << outputs[0].matrix<float>();
  return 0;
}
```
However, with the default TensorflowCC::Static target, most of the ops are indeed missing and the example does not compile. The TensorflowCC::Static uses [contrib/makefile](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile), which by default provides only basic functionality for loading and inferring using an existing network (relevant issue tensorflow/tensorflow#3017), however, it can be compiled even for Android and iOS.

For the full C++ API functionality, please use the TensorflowCC::Shared target. You don't need to have CUDA installed to build it. Just install [Bazel](https://bazel.build/) and build and install tensorflow_cc like this:
```
cd tensorflow_cc
mkdir build && cd build
cmake -DTENSORFLOW_SHARED=ON ..
make && sudo make install
```

Then link the library to your program like this:
```CMake
# CMakeLists.txt
find_package(TensorflowCC REQUIRED)
add_executable(example example.cpp)
target_link_libraries(example TensorflowCC::Shared)
```
Check out the [Dockerfiles](https://github.com/FloopCZ/tensorflow_cc/tree/master/Dockerfiles) if you are unsure or ask here. I will update the README.md to mention this problem.
