### ISSUE TITLE
Still requires building tensorflow

### ISSUE THREAD

**Issue by Christian-Prather** [FloopCZ/tensorflow_cc#300]
Hello sorry for what may be a dumb question but from the top of the readme I thought this installation did not require bazel or building tensorflow however lower in the installation section it talks about needing to do both. I am confused how this is any different from just manually building tensorflow_cc.

**Comment by FloopCZ** [comment]
Hi, you are right. You still need to _build_ tensorflow using Bazel, but this project allows you to use the resulting tensorflow library in CMake projects, which is otherwise somehow tricky (not only because of the tensorflow_cc library but also because of the header files).
