### ISSUE TITLE
 unrecognized command line option '-std=c++1z' when build example.cpp

### ISSUE THREAD

**Issue by MoyanZitto** [FloopCZ/tensorflow_cc#31]
Hi FloopCZ:

I successfully built tensorflow with your cmake script, but got "unrecognized command line option '-std=c++1z'" when building example.cpp. 
c++1z, or "C++ 17", which is supported by gcc5.x+. It's an experimental standard right now...
My gcc version is 4.8.5, and for some reason I cannot upgrade it.
So why we need C++17? And how can I do to build the example file? After all, the official tensorflow requires gcc4.8+ only...

Looking for your help, and thanks for your contribution...

**Comment by FloopCZ** [comment]
Hi, you are right, there is no need for C++ newer than 11. Please checkout the branch `cpp11` and try over, I will merge it to `dev` as soon as the tests pass.

P.S.: You should really update you compiler. ;-)

**Comment by MoyanZitto** [comment]
well, thanks for your nice response...I'll try branch cpp11.
The ops won't update the system for me╮(╯_╰)╭

**Comment by MoyanZitto** [comment]
@FloopCZ 
This post is a feedback for your cpp11 branch.
It works good! 
Man, you work saves people.

I have just recommended your repo to my colleagues, thank you again!

**Comment by FloopCZ** [comment]
Glad to hear that. :+1:
