### ISSUE TITLE
Manual input during shared library build

### ISSUE THREAD

**Issue by SergeyBykov1** [FloopCZ/tensorflow_cc#34]
My build of shared library for tf 1.4 was successful today.
cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON ..
make

But bazel asked me for two yes/no inputs.
Please add following lines to build_tensorflow.sh to solve it:
export TF_NEED_S3=0
export TF_NEED_GDR=0

**Comment by FloopCZ** [comment]
Cool, thanks!
