### ISSUE TITLE
Windows support ?

### ISSUE THREAD

**Issue by RahulSisondia** [FloopCZ/tensorflow_cc#38]
Since this project already uses CMAKE. It will be great to add support for Windows platform as well ?

**Comment by FloopCZ** [comment]
Hi, unfortunately, building on Windows [is not officially supported by Tensorflow](https://www.tensorflow.org/install/install_sources):
> We don't officially support building TensorFlow on Windows; however, you may try to build TensorFlow on Windows if you don't mind using the highly experimental Bazel on Windows or TensorFlow CMake build.

When this changes, we may think about it, but for now it is probably not worth the effort.

**Comment by guikarist** [comment]
Now [it has been changed](https://www.tensorflow.org/install/source_windows)! Would you please add support for Windows?

**Comment by FloopCZ** [comment]
Hi, I am not currently planning to add Windows support and I don't even have Windows to try it on and no CI would allow such a long process (and it would be a pain to debug in CI anyway). Nevertheless, if anyone is interested in doing this and maintaining it, feel free to open a pull request.
