### ISSUE TITLE
cudnn.h location changed for cudnn v7

### ISSUE THREAD

**Issue by sunfic** [FloopCZ/tensorflow_cc#42]
the header file cudnn.h from newest cudnn v7.04 will be installed to /usr/include rather than /usr/local/cuda/include (ubuntu 16.04). somehow it will cause some errors complaining no cudnn found. 

I manually copy the cudnn.h into /usr/local/cuda/include, it can bypass this issue.

**Comment by FloopCZ** [comment]
Thank you for the info.
ok, then we will probably need to check whether `cudnn.h` exists instead of checking whether the `cuda` folder exists. What happens with cuda headers? Are they going to be placed in `/usr/include` as well or are they going to stay in a separate `/usr/local/cuda` folder?

**Comment by sunfic** [comment]
Thanks FloopCZ,
CUDA headers remain the same location, as `/usr/local/cuda`. 
Only `cudnn` changed installation location.
