### ISSUE TITLE
Bazel build issue

### ISSUE THREAD

**Issue by sunfic** [FloopCZ/tensorflow_cc#43]
For this tensorflow Bazel build issue: [15492](https://github.com/tensorflow/tensorflow/issues/15492)

I have to modify build_tensorflow.sh line 52

`bazel build -c opt $cuda_config_opts --copt=${CC_OPT_FLAGS} tensorflow:libtensorflow_cc.so`

into

`bazel build -c opt $cuda_config_opts --incompatible_load_argument_is_label=false --copt=${CC_OPT_FLAGS} tensorflow:libtensorflow_cc.so`

to get over the errors. 

also I added  `--config=mkl` to support mkl here.

**Comment by FloopCZ** [comment]
Thank you, I will try this out.
