### ISSUE TITLE
static build with gpu supportp

### ISSUE THREAD

**Issue by redmouth** [FloopCZ/tensorflow_cc#49]
Is it possible to build .a lib with GPU support?

**Comment by FloopCZ** [comment]
No, unfortunately, not at the moment. To build a library with GPU support, we use Bazel. We are currently not able to build a static `tensorflow_cc` library with Bazel. I am not saying it is impossible, but it is probably not worth the effort. Of course, if anyone is interested a PR is welcome.

**Comment by redmouth** [comment]
So Bazel is the only choice to build with GPU support?

**Comment by FloopCZ** [comment]
There is also [CMake](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake) build with its own limitations, but again, it is probably not worth the effort to bend it for static library setup.

This project internally builds the shared library using Bazel as this is the recommended way and it is also the only way that builds a the full TF API. For static library, this project uses the [contrib/makefile](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile), which does not have a GPU support.
