### ISSUE TITLE
shared library incomplete

### ISSUE THREAD

**Issue by Rufish** [FloopCZ/tensorflow_cc#53]
Hi,
when installing the shared library my bazel-genfiles are just symbolic links to ./cache. I was able to fix it by hand, but maybe its a good idea to adjust the skript.
cheers.

**Comment by FloopCZ** [comment]
Hi, thank you for the report. I believed I have fixed it in the most recent `master` branch (~14 days ago). Have you pulled the most recent commit?

**Comment by Rufish** [comment]
Must have been an older version. Started from start and all is well. Thanks for your work, I really appreciate it.
