### ISSUE TITLE
make install installs the full 1GB contrib subfolder 

### ISSUE THREAD

**Issue by WilliamTambellini** [FloopCZ/tensorflow_cc#54]
Hi Filip
Cool project, thanks.
I am testing it on CentOS 7 and : 
- cmaking with cmake 3.9 worked well at least for static linking
- making worked well at least with gcc 4.8, and at least the CPU backend
- the libs sound good: libprotobuf.a (70MB), libtensorflow-core.a (170MB), nsync.a (80KB)
The only issue I see is that "make install" is installing the full contrib/makefile/downloads in the include subfolder, meaning about 1GB of files, including al files, not only the headers.

` 
du -sh /tmp/tfcc/include/tensorflow/tensorflow/contrib/makefile/downloads/*

3.0M    /tmp/tfcc/include/tensorflow/tensorflow/contrib/makefile/downloads/absl
3.3M    /tmp/tfcc/include/tensorflow/tensorflow/contrib/makefile/downloads/cub
17M     /tmp/tfcc/include/tensorflow/tensorflow/contrib/makefile/downloads/eigen
612K    /tmp/tfcc/include/tensorflow/tensorflow/contrib/makefile/downloads/fft2d
5.2M    /tmp/tfcc/include/tensorflow/tensorflow/contrib/makefile/downloads/gemmlowp
6.3M    /tmp/tfcc/include/tensorflow/tensorflow/contrib/makefile/downloads/googletest
2.0M    /tmp/tfcc/include/tensorflow/tensorflow/contrib/makefile/downloads/nsync
870M    /tmp/tfcc/include/tensorflow/tensorflow/contrib/makefile/downloads/protobuf
1.8M    /tmp/tfcc/include/tensorflow/tensorflow/contrib/makefile/downloads/re2
`
Is it really needed to install all downloads specially when using the static lib ?

Cheers
W.

**Comment by FloopCZ** [comment]
Hi @WilliamTambellini, thank you for the diagnosis. You are right, these files should not be necessary, I will try to skip them in the installation procedure.
