### ISSUE TITLE
Error when linking TensorflowCC to my program using CMake

### ISSUE THREAD

**Issue by kerolos** [FloopCZ/tensorflow_cc#56]
I was trying to link Tensorflow to my project by using Cmake (your method):
I did exactly what you explained in your tutorial, but I found this error:

////////////########///////////////
By not providing "FindTensorflowCC.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "TensorflowCC", but CMake did not find one.

  Could not find a package configuration file provided by "TensorflowCC" with
  any of the following names:

    TensorflowCCConfig.cmake
    tensorflowcc-config.cmake

  Add the installation prefix of "TensorflowCC" to CMAKE_PREFIX_PATH or set
  "TensorflowCC_DIR" to a directory containing one of the above files.  If
  "TensorflowCC" provides a separate development package or SDK, be sure it has been installed.
////////////########///////////////

Could you please give me some Hints to link that.
thanks in advance

**Comment by achalshah20** [comment]
I am also getting the same error. Can you please include TensorflowCCConfig.cmake file to find tensorflow cc library and all the required includes? Thanks!

**Comment by achalshah20** [comment]
My issue got resolved after doing sudo make install. @kerolos Have you done make install after doing make. Thanks!

**Comment by kerolos** [comment]
Thanks a lot  @achalshah20  for your help. i solved it by
 target_link_libraries (example TensorflowCC::Shared) instead of target_link_libraries (example ${TensorflowCC::Shared})

**Comment by FloopCZ** [comment]
Hi, sorry for the delay. Glad you fixed it.

If you want to install to userspace (without `sudo`), e.g., to folder `~/.local`, you have to configure the project with:
```
cmake -DCMAKE_INSTALL_PREFIX=~/.local ..
```

For userspace installation, don't forget to set the appropriate environmental variables in your `.bashrc` / `.zshrc`:

```
# register ~/.local system hierarchy
export PATH="${HOME}/.local/bin:$PATH"
export LIBRARY_PATH="${HOME}/.local/lib:$LIBRARY_PATH"
export LD_LIBRARY_PATH="${HOME}/.local/lib:$LD_LIBRARY_PATH"
export CPLUS_INCLUDE_PATH="${HOME}/.local/include:$CPLUS_INCLUDE_PATH"
```

**Comment by Dinu8** [comment]
I'm also getting this error when trying to link to the static library.
I have been able to build tensorflow_cc for static library and I can see TensorflowCCConfig.cmake in the build folder in tensorflow_cc/build. When I try to link TensorflowCC from example/build as it is explained in README.md I get the same error as above.
Why is example project not able to find TensorflowCCConfig.cmake in tensorflow_cc project?

This is the line producing the error:
find_package(TensorflowCC REQUIRED)

**Comment by FloopCZ** [comment]
Hi, the example does not search for `TensorflowCCConfig.cmake` in the `tensorflow_cc` folder. CMake is searching for the config file, so it has to be installed somewhere where CMake expects it. Did you run `make install` after building the project?

**Comment by Dinu8** [comment]
No, I didn't.
Thank you so much, I almost gave up.

**Comment by mmstick** [comment]
@FloopCZ Trying to package TF in a deb archive with the C / C++ / Python API, but I'm running into this issue with the shared library:

I have the root directory as `/usr/lib/tensorflow`, which contains the `include` and `lib` directories that this installs. As can be seen with the cmake files, here:

```
/usr/lib/tensorflow/lib/cmake
└── TensorflowCC
    ├── TensorflowCCConfig.cmake
    ├── TensorflowCCConfigVersion.cmake
    └── TensorflowCCSharedTargets.cmake
/usr/lib/tensorflow/lib/tensorflow_cc
├── libprotobuf.a
└── libtensorflow_cc.so
```

When setting the following (ion shell syntax for environment variables):

```
export LIBRARY_PATH = /usr/lib/tensorflow/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH = /usr/lib/tensorflow/lib:$LD_LIBRARY_PATH
export CPLUS_INCLUDE_PATH = /usr/lib/tensorflow/include:$CPLUS_INCLUDE_PATH
```

Then attempting to configure with:

```
cmake_minimum_required(VERSION 3.3 FATAL_ERROR)

find_package(TensorflowCC REQUIRED)
find_package(CUDA)

add_executable(example example.cpp)

target_link_libraries(example TensorflowCC::Shared)

if(CUDA_FOUND)
  target_link_libraries(example ${CUDA_LIBRARIES})
endif()
```

I get this error:

```
CMake Error at CMakeLists.txt:6 (add_executable):
  Target "example" links to target "TensorflowCC::Shared" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

What other actions are required to get CMake to find the files?

**Comment by achalshah20** [comment]
I have been using tensorflow_cc deb package from last 4-5 months.

It is happening because tensorflowcc.so file is in /usr/lib/tensorflow_cc. It is not in cmake rpath by default so your example is not able to find tensorflow library.

**I generally use "-DCMAKE_INSTALL_RPATH=/usr/lib/tensorflow_cc" while compiling my project. It works! **

**Comment by FloopCZ** [comment]
No, that is not the problem. The problem is that CMake cannot find the config files (by default, they should be installed in `/usr/local/lib/cmake` or `/usr/lib/cmake`, so I suppose you changed the `CMAKE_INSTALL_PREFIX`). This is not really related to `tensorflow_cc` project, though.

Are you sure your commands for env variables are correct? There should be no spaces around `=`. Check their contents by
```
echo $LD_LIBRARY_PATH
```

**Comment by achalshah20** [comment]
In that case error should be somethings like below, right ? I may be wrong but I remember I faced similar error and using rpath fixed my issue!:

```
CMake Warning at modules/PoseNN/CMakeLists.txt:27 (find_package):
  By not providing "FindTensorflowCC.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "TensorflowCC", but CMake did not find one.

  Could not find a package configuration file provided by "TensorflowCC"
  with any of the following names:

    TensorflowCCConfig.cmake
    tensorflowcc-config.cmake

  Add the installation prefix of "TensorflowCC" to CMAKE_PREFIX_PATH or set
  "TensorflowCC_DIR" to a directory containing one of the above files.  If
  "TensorflowCC" provides a separate development package or SDK, be sure it
  has been installed.
```

**Comment by FloopCZ** [comment]
Hmm, @achalshah20 there might be something in what you say. But still, I am confused, if `TensorflowCCConfig.cmake` is properly found, why aren't the `TensorflowCCSharedTargets.cmake`? The folder hierarchy seems to be correct:
```
/usr/lib/tensorflow/lib/cmake
└── TensorflowCC
    ├── TensorflowCCConfig.cmake
    ├── TensorflowCCConfigVersion.cmake
    └── TensorflowCCSharedTargets.cmake
```
@mmstick You can try to set RPATH as @achalshah20 suggests, but is it possible that you have two installations of `tensorflow_cc` and one is without the shared lib? What does
```
find /usr /home /opt -name "TensorflowCCConfig.cmake" 
```
say on your system?

**Comment by achalshah20** [comment]
Try doing find package like "find_package(TensorflowCC COMPONENTS Shared)". If it fixes your issue!

**Comment by mmstick** [comment]
After removing `/usr/lib/cmake/TensorflowCC`, I'm now getting

```
CMake Error at CMakeLists.txt:3 (find_package):
  By not providing "FindTensorflowCC.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "TensorflowCC", but CMake did not find one.

  Could not find a package configuration file provided by "TensorflowCC" with
  any of the following names:

    TensorflowCCConfig.cmake
    tensorflowcc-config.cmake

  Add the installation prefix of "TensorflowCC" to CMAKE_PREFIX_PATH or set
  "TensorflowCC_DIR" to a directory containing one of the above files.  If
  "TensorflowCC" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/mmstick/cuda-example/cc/build/CMakeFiles/CMakeOutput.log".
See also "/home/mmstick/cuda-example/cc/build/CMakeFiles/CMakeError.log".

```

**Comment by mmstick** [comment]
Setting the RPATH doesn't seem to work.

```
~/c/c/build # cmake -DCMAKE_INSTALL_RPATH=/usr/lib/tensorflow1.9-cuda9.2/lib/tensorflow_cc/ ..
CMake Error at CMakeLists.txt:3 (find_package):
  By not providing "FindTensorflowCC.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "TensorflowCC", but CMake did not find one.

  Could not find a package configuration file provided by "TensorflowCC" with
  any of the following names:

    TensorflowCCConfig.cmake
    tensorflowcc-config.cmake

  Add the installation prefix of "TensorflowCC" to CMAKE_PREFIX_PATH or set
  "TensorflowCC_DIR" to a directory containing one of the above files.  If
  "TensorflowCC" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
```

**Comment by mmstick** [comment]
Seems I can get it past that point if I add

```
list(APPEND CMAKE_PREFIX_PATH "/usr/lib/tensorflow/lib/cmake")
```

Before the `find_package`s.

**Comment by FloopCZ** [comment]
Nice. So two installations + unusual prefix.
