### ISSUE TITLE
Running C++ code on CPU with a Cuda-enabled installation of tensorflow

### ISSUE THREAD

**Issue by szm2015** [FloopCZ/tensorflow_cc#74]
Hi,
I have built your project with GPU support and it works perfectly (Thank you!), but I wish to test my code on CPU too, Is there a way to do this with the current installation? If yes, How can I do it? What lines do I need to add to my code?
If no, How can I build tensorflow_cc in CPU-only mode? I wasn't able to find any such options in CmakeLists.txt. And Is it possible to have two installations of tensorflow_cc on one system?

I really appreciate any help as I'm new to TF and wasn't able to find anything useful by Googling (just a bunch of python stuff!). Thank you!

**Comment by FloopCZ** [comment]
Hi, I am glad that `tensorflow_cc` works for you.

I am not sure if this is what you need, but if you have already built `tensorflow_cc` with GPU support, there is no need to rebuild it on order to run your program on CPU. Just launching your program with empty `CUDA_VISIBLE_DEVICES` environmental variable should do the job:
```
CUDA_VISIBLE_DEVICES="" ./my-program
```
This solution should actually work for any program utilizing CUDA, see [Accelwareblog](http://acceleware.com/blog/cudavisibledevices-masking-gpus) for more tips.

Is this what you wanted?

**Comment by szm2015** [comment]
Thank you very much! That's exactly what I need!
