### ISSUE TITLE
GCC flags causes problem with older CPUs

### ISSUE THREAD

**Issue by sailordiary** [FloopCZ/tensorflow_cc#76]
https://github.com/FloopCZ/tensorflow_cc/blob/c251135ca0d35a2af5b1311e1d4291e12774b148/tensorflow_cc/cmake/build_tensorflow.sh#L5

This line assumes a CPU later than Haswell architecture. I didn't notice this when I built the library, and my program died with the message "Illegal instruction (core dumped)".

**Comment by FloopCZ** [comment]
Yes, you are right. Just to be sure - does it work for you if you make a clean build with:
```bash
CC_OPT_FLAGS="-mtune=haswell" cmake ...
```
?

**Comment by godmoves** [comment]
@FloopCZ Still have the same problem after I add the flag `CC_OPT_FLAGS="-mtune=haswell"`.

**Comment by sailordiary** [comment]
@FloopCZ Sorry for not following up earlier. I did not try a clean build because it simply took too much time. In my case I changed the flags to -march=ivybridge to match my CPU model, and both the static and shared libraries work. Haven't tested, but I suppose -march=native works too?

**Comment by godmoves** [comment]
@sailordiary `-march=native` doesn't work for me : (

**Comment by sailordiary** [comment]
@godmoves Sorry to hear. Any luck with my way, figuring out your own CPU microarch and replacing the flags accordingly?

**Comment by godmoves** [comment]
`-march=native` finally works after I remove everything and download them again. Maybe I made some mistakes before, anyway it works this time.
