### ISSUE TITLE
Build Error when building JPEG library

### ISSUE THREAD

**Issue by dvicini** [FloopCZ/tensorflow_cc#82]
Hi, 

I have been getting the following error when building the shared library:

`
ERROR: /home/vicini/.cache/bazel/_bazel_vicini/ad1cb38aa8599cdc963f7fc2c6233006/external/jpeg/BUILD:126:12: Illegal ambiguous match on configurable attribute "deps" in @jpeg//:jpeg:
@jpeg//:k8
@jpeg//:armeabi-v7a
Multiple matches are not allowed unless one is unambiguously more specialized.
`
This error only occurs on one of the two machines I am using (cluster running Red Hat Enterprise, I dont have root access). On a laptop running OSX I got a similar error:
`
ERROR: /private/var/tmp/_bazel_vicini/9da1eaafadcdd5351e60538ddece0088/external/jpeg/BUILD:269:1: C++ compilation of rule '@jpeg//:simd_armv7a' failed (Exit 1)
error: unknown target CPU 'armv7-a'
Target //tensorflow:libtensorflow_cc.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 207.530s, Critical Path: 23.78s
FAILED: Build did NOT complete successfully
`
I've only managed to build successfully on an arch linux desktop. Any insight on whats wrong? It seems that its most likely a small configuration problem. On the OSX laptop I am also able to compile tensorflow 1.7.0 on its own (cloned directly from the main repo)...

Thanks,
Delio

**Comment by dvicini** [comment]
Nevermind, this seems to be a Tensorflow issue, when I built on the Arch linux machine I didnt have the latest version of bazel yet, which breaks the build for Tensorflow 1.7.0. 

Maybe one should change the tensorflow version being pulled by the build script?

**Comment by natsprojects** [comment]
I ran into this.  But you need Bazel 0.11.1  not the latest 0.12.0

**Comment by fli** [comment]
I could only compile it with Bazel 0.12.0 if I changed the Tensorflow tag to HEAD. You might also have success with one of the 1.8.0 release candidates.

**Comment by dvicini** [comment]
Yeah, I now switched back to using bazel 0.11.1. I will close this issue, as it seems to a be a tensorflow problem rather than a problem with the Cmake setup

**Comment by FloopCZ** [comment]
You can also try #86 if it helps you.

**Comment by yoanisgil** [comment]
I ran into the same issue and while reverting back to bazel 0.11.1 helped, I think it's still possible to make the build process a bit more flexible. So this is what I ended up doing:

First modify the Docker build file (ubuntu-cuda-shared) to be like this:

```Dockerfile
FROM nvidia/cuda:9.1-cudnn7-devel

# copy the contents of this repository to the container
COPY . tensorflow_cc
# alternatively, clone the repository
# RUN git clone https://github.com/FloopCZ/tensorflow_cc.git

# build and install
ARG TENSORFLOW_TAG=v1.6.0
ARG BAZEL_VERSION=0.11.0

RUN ./tensorflow_cc/Dockerfiles/install-ubuntu.sh
RUN ./tensorflow_cc/Dockerfiles/install-common.sh --shared --cuda
```

and then also modify `install-ubuntu.sh` like this:

```bash
if $shared; then
    # install bazel for the shared library version
    echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
    curl  https://bazel.build/bazel-release.pub.gpg | apt-key add -
    BAZEL_INSTALLER_FILENAME=bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh
    curl -L https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/${BAZEL_INSTALLER_FILENAME} > /tmp/${BAZEL_INSTALLER_FILENAME}
    chmod +x /tmp/${BAZEL_INSTALLER_FILENAME}
    /tmp/${BAZEL_INSTALLER_FILENAME}

    apt-get -y update
    apt-get -y install openjdk-8-jdk
fi
```
