### ISSUE TITLE
How can we properly uninstall tensorflow_cc for a fresh reinstallation?

### ISSUE THREAD

**Issue by szm2015** [FloopCZ/tensorflow_cc#85]
Hi,

The question is obvious in the title, I want to reinstall tensorflow_cc and so I first want to uninstall my previous attempt. It seems that there is no make uninstall option. Last time I did this I just searched for all tensorflow files and deleted the ones I thought were related to this project. Is there any other cleaner and more reliable way to do this?

Thank you!

**Comment by FloopCZ** [comment]
Hi,

So far, there is no automatic way to do it. You can use the following command to get rid of the old installation:

```
sudo rm -rv /usr/local/include/tensorflow_cc /usr/local/lib/tensorflow_cc /usr/local/lib/cmake/TensorflowCC
```
(replace `/usr/local` with whatever installation prefix you have used)

And you can also remove the whole build directory and build artifacts by something like:
```
rm -rv tensorflow_cc/build ~/.cache
```

Reinstalling over the old installation should work out-of-the-box though.
