### ISSUE TITLE
Fails with CUDA7.0

### ISSUE THREAD

**Issue by gakadam** [FloopCZ/tensorflow_cc#87]
The current release is TF 1.7 which supports CUDA7.0 as per the GitHub.
When I build tensorflow_cc, however, it fails (says cuda_f16.h missing, which I think is in later versions of CUDA). I have not tried building TF directly.
Any idea why? -- I checked some forums and apparently, TF support for CUDA-7.0 is not guaranteed.

I am trying to install TF 0.8.0 following your set-up. Did you try it?

**Comment by gakadam** [comment]
@FloopCZ Thanks for the reply. I tried few of the past versions going as far back as 0.8.0 with your set-up. 
I think it was 1.2.0, where the set-up failed because TF install procedure changed. Unfortunately, in my case, nothing worked as my CUDA version is 7.0, which is not well supported.

I think your set-up is quite robust, and at least past few versions of TF work, but many old versions have a lot of problems (incompatibilities like Bazel and others).

**Comment by FloopCZ** [comment]
You should really consider an update (or Docker). :-)
