### ISSUE TITLE
no such package '@llvm

### ISSUE THREAD

**Issue by coocoky** [FloopCZ/tensorflow_cc#88]
for shared library

cd tensorflow_cc
mkdir build && cd build
cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON ..
make && sudo make install

ERROR: /model_pose/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/compiler/xla/client/BUILD:95:1: no such package '@llvm//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/llvm-mirror/llvm/archive/195a164675af86f390f9816e53291013d1b551d7.tar.gz, https://github.com/llvm-mirror/llvm/archive/195a164675af86f390f9816e53291013d1b551d7.tar.gz] to /root/.cache/bazel/_bazel_root/51487c90485c978579d94d2832eb1b9e/external/llvm/195a164675af86f390f9816e53291013d1b551d7.tar.gz: Premature EOF and referenced by '//tensorflow/compiler/xla/client:local_client'
ERROR: Analysis of target '//tensorflow:libtensorflow_cc.so' failed; build aborted: Loading failed
INFO: Elapsed time: 1065.623s
FAILED: Build did NOT complete successfully (84 packages loaded)
CMakeFiles/tensorflow_shared.dir/build.make:106: recipe for target 'tensorflow-stamp/tensorflow_shared-configure' failed
make[2]: *** [tensorflow-stamp/tensorflow_shared-configure] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/tensorflow_shared.dir/all' failed
make[1]: *** [CMakeFiles/tensorflow_shared.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

@FloopCZ

**Comment by FloopCZ** [comment]
It seems to be a bazel llvm mirror failure. I suggest to wait. You can also try #86 if it helps you.
