### ISSUE TITLE
Not found *.pb.h on Qt config

### ISSUE THREAD

**Issue by huuson235** [FloopCZ/tensorflow_cc#9]
I am very happy to install and run successfully TF with Cmake. Thank you so much. Now my team has an old project on Qt Creator. And I want to config TF on Qt.
This is my simple Qt config. However compiler can not found *.pb.h

```
QT -= core
QT -= gui

CONFIG += c++11

TARGET = tf_test
CONFIG += console
SOURCES += main.cpp
INCLUDEPATH += /usr/local/include/tensorflow
LIBS +=  /usr/local/lib/tensorflow_cc/libprotobuf.a /usr/local/lib/tensorflow_cc/libtensorflow_cc.so

```

**Comment by FloopCZ** [comment]
Hi, with this setup, there are also plenty of other things your compiler can not see. Take a look at [CMakeLists.txt](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/CMakeLists.txt#L56) - there are many more include directories that have to be included.

**Comment by AdamHeavens** [comment]
This worked for me in using Cmake and QtCreator

TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += main.cpp

INCLUDEPATH += /usr/local/include/opencv \
               /usr/local/include/tensorflow \
               /usr/local/include/tensorflow/bazel-genfiles \
               /usr/local/include/tensorflow/tensorflow/contrib/makefile/downloads \
               /usr/local/include/tensorflow/tensorflow/contrib/makefile/downloads/eigen \
               /usr/local/include/tensorflow/tensorflow/contrib/makefile/downloads/gemmlowp \
               /usr/local/include/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/include
LIBS += /usr/local/lib/tensorflow_cc/libprotobuf.a /usr/local/lib/tensorflow_cc/libtensorflow_cc.so

**Comment by huuson235** [comment]
Thank you. It work perfectly
