### ISSUE TITLE
[Feature request] bazel build supports tensorflow_cc and pip package

### ISSUE THREAD

**Issue by achalshah20** [FloopCZ/tensorflow_cc#90]
Hi, Is it possible to build pip package along with tensorflow_cc.so? May be a optional flag to enable pip package. 

Just wondering, by adding //tensorflow/tools/pip_package:build_pip_package to the existing bazel command would just work? Thanks!

**Comment by FloopCZ** [comment]
Hi, it is theoretically possible. There would need to be an extra rule and a different list of dependencies.

However, when building the Python package, there is no need for the whole CMake infrastructure, plus you can officially download a prebuilt python package or you can use e.g., [Deepo](https://github.com/ufoym/deepo) if you like Docker. So for me, it is not currently worth the effort, it would only mean extra maintenance.
