### ISSUE TITLE
Code crashes before reaching main function

### ISSUE THREAD

**Issue by szm2015** [FloopCZ/tensorflow_cc#97]
Hi,
I have tried to build tensorflow_cc on a new system (I've already got it on two), These are the last lines of the "make" command:

`Target //tensorflow:libtensorflow_cc.so up-to-date:
  bazel-bin/tensorflow/libtensorflow_cc.so
INFO: Elapsed time: 6615.420s, Critical Path: 914.46s
INFO: Build completed successfully, 5743 total actions
find: ‘./bazel-tensorflow/external/cub_archive/tune’: No such file or directory
find: ‘./bazel-tensorflow/external/cub_archive/.settings’: No such file or directory
find: ‘./bazel-tensorflow/external/cub_archive/.cproject’: No such file or directory
find: ‘./bazel-tensorflow/external/cub_archive/LICENSE.TXT’: No such file or directory
find: ‘./bazel-tensorflow/external/cub_archive/eclipse code style profile.xml’: No such file or directory
find: ‘./bazel-tensorflow/external/cub_archive/test’: No such file or directory
find: ‘./bazel-tensorflow/external/cub_archive/WORKSPACE’: No such file or directory
find: ‘./bazel-tensorflow/external/cub_archive/common.mk’: No such file or directory
find: ‘./bazel-tensorflow/external/cub_archive/cub’: No such file or directory
find: ‘./bazel-tensorflow/external/com_google_absl’: No such file or directory
find: ‘./bazel-tensorflow/external/png_archive’: No such file or directory
find: ‘./bazel-tensorflow/external/local_jdk’: No such file or directory
find: ‘./bazel-tensorflow/external/eigen_archive’: No such file or directory
find: ‘./bazel-tensorflow/external/snappy’: No such file or directory
find: ‘./bazel-tensorflow/external/jemalloc’: No such file or directory
find: ‘./bazel-tensorflow/external/jpeg’: No such file or directory
find: ‘./bazel-tensorflow/external/farmhash_archive’: No such file or directory
find: ‘./bazel-tensorflow/external/local_config_git’: No such file or directory
find: ‘./bazel-tensorflow/external/local_config_sycl’: No such file or directory
find: ‘./bazel-tensorflow/external/bazel_tools’: No such file or directory
find: ‘./bazel-tensorflow/external/gemmlowp’: No such file or directory
find: ‘./bazel-tensorflow/external/llvm’: No such file or directory
find: ‘./bazel-tensorflow/external/nasm’: No such file or directory
find: ‘./bazel-tensorflow/external/com_googlesource_code_re2’: No such file or directory
find: ‘./bazel-tensorflow/external/jsoncpp_git’: No such file or directory
find: ‘./bazel-tensorflow/external/nsync’: No such file or directory
find: ‘./bazel-tensorflow/external/gif_archive’: No such file or directory
find: ‘./bazel-tensorflow/external/org_tensorflow’: No such file or directory
find: ‘./bazel-tensorflow/external/lmdb’: No such file or directory
find: ‘./bazel-tensorflow/external/zlib_archive’: No such file or directory
find: ‘./bazel-tensorflow/external/local_config_cuda’: No such file or directory
find: ‘./bazel-tensorflow/external/org_sqlite’: No such file or directory
find: ‘./bazel-tensorflow/external/fft2d’: No such file or directory
find: ‘./bazel-tensorflow/external/protobuf_archive’: No such file or directory
find: ‘./bazel-tensorflow/bazel-out’: No such file or directory
find: ‘./bazel-tensorflow/tensorflow’: No such file or directory
find: ‘./bazel-tensorflow/third_party’: No such file or directory
[ 87%] No build step for 'tensorflow_shared'
[ 93%] No install step for 'tensorflow_shared'
[100%] Completed 'tensorflow_shared'
[100%] Built target tensorflow_shared`

I have no idea about the lines like "find: ‘./bazel-tensorflow/third_party’: No such file or directory" but anyway I tried to build a cpp code with it (the one that I'm using on other systems without a problem), It builds all right but the code crashes before it even reaches the main which makes me think that the problem is with the tensorflow fuctions and libraries being linked.

I would appreciate any help. Thank you.

**Comment by FloopCZ** [comment]
Hi, this is probably not an error.

There is an "unlink" process at the end of the build, and those lines only mean that the parent directory was already "unlinked". I also encounter this, but it does not break anything. What if you do `make install` and than build and run the example? Does it work for you?

**Comment by szm2015** [comment]
Well, I have issued the make install command and the thing I'm talking about (program crashing before main) occurs after that. I have no idea what could cause this problem.

**Comment by FloopCZ** [comment]
Can you try the `v1.8.0` branch please?

**Comment by FloopCZ** [comment]
And also provide the output of the actual failure of the program.

**Comment by yoanisgil** [comment]
Would also be nice to know what is your build method? I assume it's not Docker ...

**Comment by szm2015** [comment]
I'm not using the Docker. I git cloned the repository yesterday and then followed the instructions provided for building the project as a shared library. How can I try the 1.8.0 version? should I change the tf version in CmakeList.txt?

About the actual failure of the program, it doesn't give me anything special just that when I run it I get this output:
Illegal instruction (core dumped)

And when I debug it, the code crashes before even entering the main function.

**Comment by yoanisgil** [comment]
I think 1.8.0 is a branch. Try `git checkout v1.8.0`.

**Comment by yoanisgil** [comment]
Also, it would help if you paste the steps to reproduce the issue. That way we can try to replicate them on our side.

**Comment by FloopCZ** [comment]
If it gives `Illegal instruction`, I suppose that you have a CPU older than `haswell`, right? I addressed this by a [note](https://github.com/FloopCZ/tensorflow_cc/pull/86/files#diff-04c6e90faac2675aa89e2176d2eec7d8R96) in the readme in the `v1.8.0` branch:

**Warning:** Optimizations for Intel CPU series `>=haswell` are enabled by default. If you have a
processor that is older than `haswell` series, you may wish to run `export CC_OPT_FLAGS="-march=native"` before the build.

**Comment by szm2015** [comment]
OK, my CPU is Core i7, I think then it's older than Haswell right? So do I
still need to move to 1.8.0 version or try that line you mentioned in this
same version I got now?

**Comment by FloopCZ** [comment]
It depends on what is the generation of the processor. You might have i7 Ivy Bridge that is older, or i7 Kaby Lake that is newer. So hard to say. :-)

Unless you want to migrate the built library between computers (probably not), use the
```
export CC_OPT_FLAGS="-march=native"`
```
before build. It should fix your issue, you don't need to use TensorFlow 1.8.0.

The `v1.8.0` branch is now merged in `master`.

**Comment by szm2015** [comment]
Thank you very much! I cloned the newest version and then issued the
command you said, before build. Now everything works perfectly!
